// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.4.0
//   protoc               v6.32.1
// source: api.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export interface Empty {
}

/** Address represents an IP address. */
export interface Address {
  id: number;
  createdAt: number;
  updatedAt: number;
  ip: string;
  current: boolean;
}

export interface AddressHistory {
  addresses: Address[];
}

/** Record represents a DNS record. */
export interface Record {
  id: number;
  createdAt: number;
  updatedAt: number;
  token: string;
  zoneId: string;
  domain: string;
  name: string;
  ttl: number;
  addressId?: number | undefined;
  address?: Address | undefined;
  lastRefresh?: number | undefined;
}

export interface RecordList {
  records: Record[];
}

export interface Zone {
  id: string;
  name: string;
  recordCount: number;
}

export interface ZoneList {
  zones: Zone[];
}

export interface Resolution {
  server: string;
  addresses: string[];
  responseTime: number;
  error: string;
}

export interface ResolutionResult {
  resolutions: Resolution[];
}

export interface Configuration {
  service: Service | undefined;
  database: Database | undefined;
}

export interface Service {
  logLevel: number;
  webPort: number;
  certificatePath: string;
  keyPath: string;
  refreshCron: string;
  dnsServers: string[];
  ipv4Resolvers: string[];
  ipv6Resolvers: string[];
}

export interface Database {
  host: string;
  port: number;
  username: string;
  password: string;
  name: string;
}

export interface LogEntry {
  timestamp: number;
  level: number;
  message: string;
}

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

function createBaseAddress(): Address {
  return { id: 0, createdAt: 0, updatedAt: 0, ip: "", current: false };
}

export const Address: MessageFns<Address> = {
  encode(message: Address, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.createdAt !== 0) {
      writer.uint32(16).int64(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      writer.uint32(24).int64(message.updatedAt);
    }
    if (message.ip !== "") {
      writer.uint32(34).string(message.ip);
    }
    if (message.current !== false) {
      writer.uint32(40).bool(message.current);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Address {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.createdAt = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.updatedAt = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ip = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.current = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Address {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      createdAt: isSet(object.createdAt) ? globalThis.Number(object.createdAt) : 0,
      updatedAt: isSet(object.updatedAt) ? globalThis.Number(object.updatedAt) : 0,
      ip: isSet(object.ip) ? globalThis.String(object.ip) : "",
      current: isSet(object.current) ? globalThis.Boolean(object.current) : false,
    };
  },

  toJSON(message: Address): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      obj.updatedAt = Math.round(message.updatedAt);
    }
    if (message.ip !== "") {
      obj.ip = message.ip;
    }
    if (message.current !== false) {
      obj.current = message.current;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Address>, I>>(base?: I): Address {
    return Address.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Address>, I>>(object: I): Address {
    const message = createBaseAddress();
    message.id = object.id ?? 0;
    message.createdAt = object.createdAt ?? 0;
    message.updatedAt = object.updatedAt ?? 0;
    message.ip = object.ip ?? "";
    message.current = object.current ?? false;
    return message;
  },
};

function createBaseAddressHistory(): AddressHistory {
  return { addresses: [] };
}

export const AddressHistory: MessageFns<AddressHistory> = {
  encode(message: AddressHistory, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.addresses) {
      Address.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddressHistory {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddressHistory();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.addresses.push(Address.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddressHistory {
    return {
      addresses: globalThis.Array.isArray(object?.addresses)
        ? object.addresses.map((e: any) => Address.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AddressHistory): unknown {
    const obj: any = {};
    if (message.addresses?.length) {
      obj.addresses = message.addresses.map((e) => Address.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddressHistory>, I>>(base?: I): AddressHistory {
    return AddressHistory.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddressHistory>, I>>(object: I): AddressHistory {
    const message = createBaseAddressHistory();
    message.addresses = object.addresses?.map((e) => Address.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRecord(): Record {
  return {
    id: 0,
    createdAt: 0,
    updatedAt: 0,
    token: "",
    zoneId: "",
    domain: "",
    name: "",
    ttl: 0,
    addressId: undefined,
    address: undefined,
    lastRefresh: undefined,
  };
}

export const Record: MessageFns<Record> = {
  encode(message: Record, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.createdAt !== 0) {
      writer.uint32(16).int64(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      writer.uint32(24).int64(message.updatedAt);
    }
    if (message.token !== "") {
      writer.uint32(34).string(message.token);
    }
    if (message.zoneId !== "") {
      writer.uint32(42).string(message.zoneId);
    }
    if (message.domain !== "") {
      writer.uint32(50).string(message.domain);
    }
    if (message.name !== "") {
      writer.uint32(58).string(message.name);
    }
    if (message.ttl !== 0) {
      writer.uint32(64).uint32(message.ttl);
    }
    if (message.addressId !== undefined) {
      writer.uint32(72).int64(message.addressId);
    }
    if (message.address !== undefined) {
      Address.encode(message.address, writer.uint32(82).fork()).join();
    }
    if (message.lastRefresh !== undefined) {
      writer.uint32(88).int64(message.lastRefresh);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Record {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.createdAt = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.updatedAt = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.zoneId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.ttl = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.addressId = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.address = Address.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.lastRefresh = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Record {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      createdAt: isSet(object.createdAt) ? globalThis.Number(object.createdAt) : 0,
      updatedAt: isSet(object.updatedAt) ? globalThis.Number(object.updatedAt) : 0,
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      zoneId: isSet(object.zoneId) ? globalThis.String(object.zoneId) : "",
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      ttl: isSet(object.ttl) ? globalThis.Number(object.ttl) : 0,
      addressId: isSet(object.addressId) ? globalThis.Number(object.addressId) : undefined,
      address: isSet(object.address) ? Address.fromJSON(object.address) : undefined,
      lastRefresh: isSet(object.lastRefresh) ? globalThis.Number(object.lastRefresh) : undefined,
    };
  },

  toJSON(message: Record): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      obj.updatedAt = Math.round(message.updatedAt);
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.zoneId !== "") {
      obj.zoneId = message.zoneId;
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.ttl !== 0) {
      obj.ttl = Math.round(message.ttl);
    }
    if (message.addressId !== undefined) {
      obj.addressId = Math.round(message.addressId);
    }
    if (message.address !== undefined) {
      obj.address = Address.toJSON(message.address);
    }
    if (message.lastRefresh !== undefined) {
      obj.lastRefresh = Math.round(message.lastRefresh);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Record>, I>>(base?: I): Record {
    return Record.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Record>, I>>(object: I): Record {
    const message = createBaseRecord();
    message.id = object.id ?? 0;
    message.createdAt = object.createdAt ?? 0;
    message.updatedAt = object.updatedAt ?? 0;
    message.token = object.token ?? "";
    message.zoneId = object.zoneId ?? "";
    message.domain = object.domain ?? "";
    message.name = object.name ?? "";
    message.ttl = object.ttl ?? 0;
    message.addressId = object.addressId ?? undefined;
    message.address = (object.address !== undefined && object.address !== null)
      ? Address.fromPartial(object.address)
      : undefined;
    message.lastRefresh = object.lastRefresh ?? undefined;
    return message;
  },
};

function createBaseRecordList(): RecordList {
  return { records: [] };
}

export const RecordList: MessageFns<RecordList> = {
  encode(message: RecordList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.records) {
      Record.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecordList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecordList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.records.push(Record.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RecordList {
    return {
      records: globalThis.Array.isArray(object?.records) ? object.records.map((e: any) => Record.fromJSON(e)) : [],
    };
  },

  toJSON(message: RecordList): unknown {
    const obj: any = {};
    if (message.records?.length) {
      obj.records = message.records.map((e) => Record.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RecordList>, I>>(base?: I): RecordList {
    return RecordList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecordList>, I>>(object: I): RecordList {
    const message = createBaseRecordList();
    message.records = object.records?.map((e) => Record.fromPartial(e)) || [];
    return message;
  },
};

function createBaseZone(): Zone {
  return { id: "", name: "", recordCount: 0 };
}

export const Zone: MessageFns<Zone> = {
  encode(message: Zone, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.recordCount !== 0) {
      writer.uint32(24).int64(message.recordCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Zone {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseZone();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.recordCount = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Zone {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      recordCount: isSet(object.recordCount) ? globalThis.Number(object.recordCount) : 0,
    };
  },

  toJSON(message: Zone): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.recordCount !== 0) {
      obj.recordCount = Math.round(message.recordCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Zone>, I>>(base?: I): Zone {
    return Zone.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Zone>, I>>(object: I): Zone {
    const message = createBaseZone();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.recordCount = object.recordCount ?? 0;
    return message;
  },
};

function createBaseZoneList(): ZoneList {
  return { zones: [] };
}

export const ZoneList: MessageFns<ZoneList> = {
  encode(message: ZoneList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.zones) {
      Zone.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ZoneList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseZoneList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.zones.push(Zone.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ZoneList {
    return { zones: globalThis.Array.isArray(object?.zones) ? object.zones.map((e: any) => Zone.fromJSON(e)) : [] };
  },

  toJSON(message: ZoneList): unknown {
    const obj: any = {};
    if (message.zones?.length) {
      obj.zones = message.zones.map((e) => Zone.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ZoneList>, I>>(base?: I): ZoneList {
    return ZoneList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ZoneList>, I>>(object: I): ZoneList {
    const message = createBaseZoneList();
    message.zones = object.zones?.map((e) => Zone.fromPartial(e)) || [];
    return message;
  },
};

function createBaseResolution(): Resolution {
  return { server: "", addresses: [], responseTime: 0, error: "" };
}

export const Resolution: MessageFns<Resolution> = {
  encode(message: Resolution, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.server !== "") {
      writer.uint32(10).string(message.server);
    }
    for (const v of message.addresses) {
      writer.uint32(18).string(v!);
    }
    if (message.responseTime !== 0) {
      writer.uint32(24).int64(message.responseTime);
    }
    if (message.error !== "") {
      writer.uint32(34).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Resolution {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResolution();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.server = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.addresses.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.responseTime = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Resolution {
    return {
      server: isSet(object.server) ? globalThis.String(object.server) : "",
      addresses: globalThis.Array.isArray(object?.addresses)
        ? object.addresses.map((e: any) => globalThis.String(e))
        : [],
      responseTime: isSet(object.responseTime) ? globalThis.Number(object.responseTime) : 0,
      error: isSet(object.error) ? globalThis.String(object.error) : "",
    };
  },

  toJSON(message: Resolution): unknown {
    const obj: any = {};
    if (message.server !== "") {
      obj.server = message.server;
    }
    if (message.addresses?.length) {
      obj.addresses = message.addresses;
    }
    if (message.responseTime !== 0) {
      obj.responseTime = Math.round(message.responseTime);
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Resolution>, I>>(base?: I): Resolution {
    return Resolution.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Resolution>, I>>(object: I): Resolution {
    const message = createBaseResolution();
    message.server = object.server ?? "";
    message.addresses = object.addresses?.map((e) => e) || [];
    message.responseTime = object.responseTime ?? 0;
    message.error = object.error ?? "";
    return message;
  },
};

function createBaseResolutionResult(): ResolutionResult {
  return { resolutions: [] };
}

export const ResolutionResult: MessageFns<ResolutionResult> = {
  encode(message: ResolutionResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.resolutions) {
      Resolution.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResolutionResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResolutionResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.resolutions.push(Resolution.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResolutionResult {
    return {
      resolutions: globalThis.Array.isArray(object?.resolutions)
        ? object.resolutions.map((e: any) => Resolution.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ResolutionResult): unknown {
    const obj: any = {};
    if (message.resolutions?.length) {
      obj.resolutions = message.resolutions.map((e) => Resolution.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResolutionResult>, I>>(base?: I): ResolutionResult {
    return ResolutionResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResolutionResult>, I>>(object: I): ResolutionResult {
    const message = createBaseResolutionResult();
    message.resolutions = object.resolutions?.map((e) => Resolution.fromPartial(e)) || [];
    return message;
  },
};

function createBaseConfiguration(): Configuration {
  return { service: undefined, database: undefined };
}

export const Configuration: MessageFns<Configuration> = {
  encode(message: Configuration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.service !== undefined) {
      Service.encode(message.service, writer.uint32(10).fork()).join();
    }
    if (message.database !== undefined) {
      Database.encode(message.database, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Configuration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfiguration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.service = Service.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.database = Database.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Configuration {
    return {
      service: isSet(object.service) ? Service.fromJSON(object.service) : undefined,
      database: isSet(object.database) ? Database.fromJSON(object.database) : undefined,
    };
  },

  toJSON(message: Configuration): unknown {
    const obj: any = {};
    if (message.service !== undefined) {
      obj.service = Service.toJSON(message.service);
    }
    if (message.database !== undefined) {
      obj.database = Database.toJSON(message.database);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Configuration>, I>>(base?: I): Configuration {
    return Configuration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Configuration>, I>>(object: I): Configuration {
    const message = createBaseConfiguration();
    message.service = (object.service !== undefined && object.service !== null)
      ? Service.fromPartial(object.service)
      : undefined;
    message.database = (object.database !== undefined && object.database !== null)
      ? Database.fromPartial(object.database)
      : undefined;
    return message;
  },
};

function createBaseService(): Service {
  return {
    logLevel: 0,
    webPort: 0,
    certificatePath: "",
    keyPath: "",
    refreshCron: "",
    dnsServers: [],
    ipv4Resolvers: [],
    ipv6Resolvers: [],
  };
}

export const Service: MessageFns<Service> = {
  encode(message: Service, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.logLevel !== 0) {
      writer.uint32(8).int32(message.logLevel);
    }
    if (message.webPort !== 0) {
      writer.uint32(16).int32(message.webPort);
    }
    if (message.certificatePath !== "") {
      writer.uint32(26).string(message.certificatePath);
    }
    if (message.keyPath !== "") {
      writer.uint32(34).string(message.keyPath);
    }
    if (message.refreshCron !== "") {
      writer.uint32(42).string(message.refreshCron);
    }
    for (const v of message.dnsServers) {
      writer.uint32(50).string(v!);
    }
    for (const v of message.ipv4Resolvers) {
      writer.uint32(58).string(v!);
    }
    for (const v of message.ipv6Resolvers) {
      writer.uint32(66).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Service {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseService();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.logLevel = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.webPort = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.certificatePath = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.keyPath = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.refreshCron = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.dnsServers.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.ipv4Resolvers.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.ipv6Resolvers.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Service {
    return {
      logLevel: isSet(object.logLevel) ? globalThis.Number(object.logLevel) : 0,
      webPort: isSet(object.webPort) ? globalThis.Number(object.webPort) : 0,
      certificatePath: isSet(object.certificatePath) ? globalThis.String(object.certificatePath) : "",
      keyPath: isSet(object.keyPath) ? globalThis.String(object.keyPath) : "",
      refreshCron: isSet(object.refreshCron) ? globalThis.String(object.refreshCron) : "",
      dnsServers: globalThis.Array.isArray(object?.dnsServers)
        ? object.dnsServers.map((e: any) => globalThis.String(e))
        : [],
      ipv4Resolvers: globalThis.Array.isArray(object?.ipv4Resolvers)
        ? object.ipv4Resolvers.map((e: any) => globalThis.String(e))
        : [],
      ipv6Resolvers: globalThis.Array.isArray(object?.ipv6Resolvers)
        ? object.ipv6Resolvers.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: Service): unknown {
    const obj: any = {};
    if (message.logLevel !== 0) {
      obj.logLevel = Math.round(message.logLevel);
    }
    if (message.webPort !== 0) {
      obj.webPort = Math.round(message.webPort);
    }
    if (message.certificatePath !== "") {
      obj.certificatePath = message.certificatePath;
    }
    if (message.keyPath !== "") {
      obj.keyPath = message.keyPath;
    }
    if (message.refreshCron !== "") {
      obj.refreshCron = message.refreshCron;
    }
    if (message.dnsServers?.length) {
      obj.dnsServers = message.dnsServers;
    }
    if (message.ipv4Resolvers?.length) {
      obj.ipv4Resolvers = message.ipv4Resolvers;
    }
    if (message.ipv6Resolvers?.length) {
      obj.ipv6Resolvers = message.ipv6Resolvers;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Service>, I>>(base?: I): Service {
    return Service.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Service>, I>>(object: I): Service {
    const message = createBaseService();
    message.logLevel = object.logLevel ?? 0;
    message.webPort = object.webPort ?? 0;
    message.certificatePath = object.certificatePath ?? "";
    message.keyPath = object.keyPath ?? "";
    message.refreshCron = object.refreshCron ?? "";
    message.dnsServers = object.dnsServers?.map((e) => e) || [];
    message.ipv4Resolvers = object.ipv4Resolvers?.map((e) => e) || [];
    message.ipv6Resolvers = object.ipv6Resolvers?.map((e) => e) || [];
    return message;
  },
};

function createBaseDatabase(): Database {
  return { host: "", port: 0, username: "", password: "", name: "" };
}

export const Database: MessageFns<Database> = {
  encode(message: Database, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.host !== "") {
      writer.uint32(10).string(message.host);
    }
    if (message.port !== 0) {
      writer.uint32(16).uint32(message.port);
    }
    if (message.username !== "") {
      writer.uint32(26).string(message.username);
    }
    if (message.password !== "") {
      writer.uint32(34).string(message.password);
    }
    if (message.name !== "") {
      writer.uint32(42).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Database {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDatabase();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.host = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.port = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Database {
    return {
      host: isSet(object.host) ? globalThis.String(object.host) : "",
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: Database): unknown {
    const obj: any = {};
    if (message.host !== "") {
      obj.host = message.host;
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Database>, I>>(base?: I): Database {
    return Database.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Database>, I>>(object: I): Database {
    const message = createBaseDatabase();
    message.host = object.host ?? "";
    message.port = object.port ?? 0;
    message.username = object.username ?? "";
    message.password = object.password ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseLogEntry(): LogEntry {
  return { timestamp: 0, level: 0, message: "" };
}

export const LogEntry: MessageFns<LogEntry> = {
  encode(message: LogEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestamp !== 0) {
      writer.uint32(8).int64(message.timestamp);
    }
    if (message.level !== 0) {
      writer.uint32(16).int32(message.level);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.level = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogEntry {
    return {
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: LogEntry): unknown {
    const obj: any = {};
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogEntry>, I>>(base?: I): LogEntry {
    return LogEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogEntry>, I>>(object: I): LogEntry {
    const message = createBaseLogEntry();
    message.timestamp = object.timestamp ?? 0;
    message.level = object.level ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
