// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: api.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export enum RecordPurpose {
  RECORD_PURPOSE_UNSPECIFIED = 0,
  RECORD_PURPOSE_DDNS = 1,
  RECORD_PURPOSE_CERT = 2,
  RECORD_PURPOSE_BOTH = 3,
  UNRECOGNIZED = -1,
}

export function recordPurposeFromJSON(object: any): RecordPurpose {
  switch (object) {
    case 0:
    case "RECORD_PURPOSE_UNSPECIFIED":
      return RecordPurpose.RECORD_PURPOSE_UNSPECIFIED;
    case 1:
    case "RECORD_PURPOSE_DDNS":
      return RecordPurpose.RECORD_PURPOSE_DDNS;
    case 2:
    case "RECORD_PURPOSE_CERT":
      return RecordPurpose.RECORD_PURPOSE_CERT;
    case 3:
    case "RECORD_PURPOSE_BOTH":
      return RecordPurpose.RECORD_PURPOSE_BOTH;
    case -1:
    case "UNRECOGNIZED":
    default:
      return RecordPurpose.UNRECOGNIZED;
  }
}

export function recordPurposeToJSON(object: RecordPurpose): string {
  switch (object) {
    case RecordPurpose.RECORD_PURPOSE_UNSPECIFIED:
      return "RECORD_PURPOSE_UNSPECIFIED";
    case RecordPurpose.RECORD_PURPOSE_DDNS:
      return "RECORD_PURPOSE_DDNS";
    case RecordPurpose.RECORD_PURPOSE_CERT:
      return "RECORD_PURPOSE_CERT";
    case RecordPurpose.RECORD_PURPOSE_BOTH:
      return "RECORD_PURPOSE_BOTH";
    case RecordPurpose.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum TaskTrigger {
  TASK_TRIGGER_UNSPECIFIED = 0,
  TASK_TRIGGER_IP = 1,
  TASK_TRIGGER_CERT = 2,
  TASK_TRIGGER_BOTH = 3,
  UNRECOGNIZED = -1,
}

export function taskTriggerFromJSON(object: any): TaskTrigger {
  switch (object) {
    case 0:
    case "TASK_TRIGGER_UNSPECIFIED":
      return TaskTrigger.TASK_TRIGGER_UNSPECIFIED;
    case 1:
    case "TASK_TRIGGER_IP":
      return TaskTrigger.TASK_TRIGGER_IP;
    case 2:
    case "TASK_TRIGGER_CERT":
      return TaskTrigger.TASK_TRIGGER_CERT;
    case 3:
    case "TASK_TRIGGER_BOTH":
      return TaskTrigger.TASK_TRIGGER_BOTH;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TaskTrigger.UNRECOGNIZED;
  }
}

export function taskTriggerToJSON(object: TaskTrigger): string {
  switch (object) {
    case TaskTrigger.TASK_TRIGGER_UNSPECIFIED:
      return "TASK_TRIGGER_UNSPECIFIED";
    case TaskTrigger.TASK_TRIGGER_IP:
      return "TASK_TRIGGER_IP";
    case TaskTrigger.TASK_TRIGGER_CERT:
      return "TASK_TRIGGER_CERT";
    case TaskTrigger.TASK_TRIGGER_BOTH:
      return "TASK_TRIGGER_BOTH";
    case TaskTrigger.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Empty {
}

export interface Request {
  search: string;
}

export interface ZoneRequest {
  token: string;
}

/** Address represents an IP address. */
export interface Address {
  id: number;
  createdAt: number;
  updatedAt: number;
  ipv4: string;
  ipv6: string;
  current: boolean;
}

export interface AddressHistory {
  addresses: Address[];
}

/** Record represents a DNS record. */
export interface Record {
  id: number;
  createdAt: number;
  updatedAt: number;
  token: string;
  zoneId: number;
  domain: string;
  name: string;
  ttl: number;
  addressId: number;
  address: Address | undefined;
  purpose: RecordPurpose;
  includeWildcard: boolean;
  certificate: Certificate | undefined;
}

export interface RecordList {
  records: Record[];
}

export interface RecordDelete {
  record: Record | undefined;
  deleteFromHetzner: boolean;
}

/** Certificate represents an issued Let's Encrypt certificate. */
export interface Certificate {
  id: number;
  createdAt: number;
  updatedAt: number;
  recordId: number;
  domains: string;
  status: string;
  notBefore: number;
  notAfter: number;
  serial: string;
  lastError: string;
}

export interface CertificateList {
  certificates: Certificate[];
}

/** Task represents a webhook executed on IP or certificate renewal. */
export interface Task {
  id: number;
  createdAt: number;
  updatedAt: number;
  recordId: number;
  name: string;
  triggerOn: TaskTrigger;
  method: string;
  url: string;
  /**
   * headers is a JSON object of HTTP headers. It is write-only and never
   * returned populated to avoid exposing secrets.
   */
  headers: string;
  body: string;
  enabled: boolean;
  lastRun: number;
  lastStatus: string;
  lastError: string;
  /**
   * include_certificate injects the issued certificate and private key into the
   * webhook body via the {{certificate}} and {{private_key}} placeholders.
   */
  includeCertificate: boolean;
}

export interface TaskList {
  tasks: Task[];
}

export interface TaskDelete {
  id: number;
}

export interface TaskResult {
  status: string;
  error: string;
}

export interface Zone {
  id: number;
  name: string;
  recordCount: number;
}

export interface ZoneList {
  zones: Zone[];
}

export interface Resolution {
  server: string;
  addresses: string[];
  responseTime: number;
  error: string;
}

export interface ResolutionResult {
  resolutions: Resolution[];
}

export interface Configuration {
  logLevel: number;
  refreshCron: string;
  dnsServers: string[];
  ipv4Resolvers: string[];
  ipv6Resolvers: string[];
  /**
   * User-facing notification settings. SMTP transport (host, port, auth, TLS,
   * from address, ...) is intentionally NOT part of this message and is
   * configured via the YAML file only.
   */
  notificationsEnabled: boolean;
  notificationsOnSuccess: boolean;
  notificationsRecipients: string[];
  notificationsCooldownMinutes: number;
  notificationsSubjectPrefix: string;
  /** ACME / Let's Encrypt settings for DNS-01 certificate issuance. */
  acmeEnabled: boolean;
  acmeEmail: string;
  acmeStaging: boolean;
  acmeRenewBeforeDays: number;
}

export interface LogEntry {
  timestamp: number;
  level: number;
  message: string;
}

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

function createBaseRequest(): Request {
  return { search: "" };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.search !== "") {
      writer.uint32(10).string(message.search);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.search = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return { search: isSet(object.search) ? globalThis.String(object.search) : "" };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.search !== "") {
      obj.search = message.search;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.search = object.search ?? "";
    return message;
  },
};

function createBaseZoneRequest(): ZoneRequest {
  return { token: "" };
}

export const ZoneRequest: MessageFns<ZoneRequest> = {
  encode(message: ZoneRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ZoneRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseZoneRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ZoneRequest {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: ZoneRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ZoneRequest>, I>>(base?: I): ZoneRequest {
    return ZoneRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ZoneRequest>, I>>(object: I): ZoneRequest {
    const message = createBaseZoneRequest();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseAddress(): Address {
  return { id: 0, createdAt: 0, updatedAt: 0, ipv4: "", ipv6: "", current: false };
}

export const Address: MessageFns<Address> = {
  encode(message: Address, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.createdAt !== 0) {
      writer.uint32(16).int64(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      writer.uint32(24).int64(message.updatedAt);
    }
    if (message.ipv4 !== "") {
      writer.uint32(34).string(message.ipv4);
    }
    if (message.ipv6 !== "") {
      writer.uint32(42).string(message.ipv6);
    }
    if (message.current !== false) {
      writer.uint32(48).bool(message.current);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Address {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.createdAt = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.updatedAt = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ipv4 = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.ipv6 = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.current = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Address {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      createdAt: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      updatedAt: isSet(object.updatedAt)
        ? globalThis.Number(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.Number(object.updated_at)
        : 0,
      ipv4: isSet(object.ipv4) ? globalThis.String(object.ipv4) : "",
      ipv6: isSet(object.ipv6) ? globalThis.String(object.ipv6) : "",
      current: isSet(object.current) ? globalThis.Boolean(object.current) : false,
    };
  },

  toJSON(message: Address): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      obj.updatedAt = Math.round(message.updatedAt);
    }
    if (message.ipv4 !== "") {
      obj.ipv4 = message.ipv4;
    }
    if (message.ipv6 !== "") {
      obj.ipv6 = message.ipv6;
    }
    if (message.current !== false) {
      obj.current = message.current;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Address>, I>>(base?: I): Address {
    return Address.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Address>, I>>(object: I): Address {
    const message = createBaseAddress();
    message.id = object.id ?? 0;
    message.createdAt = object.createdAt ?? 0;
    message.updatedAt = object.updatedAt ?? 0;
    message.ipv4 = object.ipv4 ?? "";
    message.ipv6 = object.ipv6 ?? "";
    message.current = object.current ?? false;
    return message;
  },
};

function createBaseAddressHistory(): AddressHistory {
  return { addresses: [] };
}

export const AddressHistory: MessageFns<AddressHistory> = {
  encode(message: AddressHistory, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.addresses) {
      Address.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddressHistory {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddressHistory();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.addresses.push(Address.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddressHistory {
    return {
      addresses: globalThis.Array.isArray(object?.addresses)
        ? object.addresses.map((e: any) => Address.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AddressHistory): unknown {
    const obj: any = {};
    if (message.addresses?.length) {
      obj.addresses = message.addresses.map((e) => Address.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddressHistory>, I>>(base?: I): AddressHistory {
    return AddressHistory.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddressHistory>, I>>(object: I): AddressHistory {
    const message = createBaseAddressHistory();
    message.addresses = object.addresses?.map((e) => Address.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRecord(): Record {
  return {
    id: 0,
    createdAt: 0,
    updatedAt: 0,
    token: "",
    zoneId: 0,
    domain: "",
    name: "",
    ttl: 0,
    addressId: 0,
    address: undefined,
    purpose: 0,
    includeWildcard: false,
    certificate: undefined,
  };
}

export const Record: MessageFns<Record> = {
  encode(message: Record, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.createdAt !== 0) {
      writer.uint32(16).int64(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      writer.uint32(24).int64(message.updatedAt);
    }
    if (message.token !== "") {
      writer.uint32(34).string(message.token);
    }
    if (message.zoneId !== 0) {
      writer.uint32(40).int64(message.zoneId);
    }
    if (message.domain !== "") {
      writer.uint32(50).string(message.domain);
    }
    if (message.name !== "") {
      writer.uint32(58).string(message.name);
    }
    if (message.ttl !== 0) {
      writer.uint32(64).uint32(message.ttl);
    }
    if (message.addressId !== 0) {
      writer.uint32(72).int64(message.addressId);
    }
    if (message.address !== undefined) {
      Address.encode(message.address, writer.uint32(82).fork()).join();
    }
    if (message.purpose !== 0) {
      writer.uint32(88).int32(message.purpose);
    }
    if (message.includeWildcard !== false) {
      writer.uint32(96).bool(message.includeWildcard);
    }
    if (message.certificate !== undefined) {
      Certificate.encode(message.certificate, writer.uint32(106).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Record {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.createdAt = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.updatedAt = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.zoneId = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.ttl = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.addressId = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.address = Address.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.purpose = reader.int32() as any;
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.includeWildcard = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.certificate = Certificate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Record {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      createdAt: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      updatedAt: isSet(object.updatedAt)
        ? globalThis.Number(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.Number(object.updated_at)
        : 0,
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      zoneId: isSet(object.zoneId)
        ? globalThis.Number(object.zoneId)
        : isSet(object.zone_id)
        ? globalThis.Number(object.zone_id)
        : 0,
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      ttl: isSet(object.ttl) ? globalThis.Number(object.ttl) : 0,
      addressId: isSet(object.addressId)
        ? globalThis.Number(object.addressId)
        : isSet(object.address_id)
        ? globalThis.Number(object.address_id)
        : 0,
      address: isSet(object.address) ? Address.fromJSON(object.address) : undefined,
      purpose: isSet(object.purpose) ? recordPurposeFromJSON(object.purpose) : 0,
      includeWildcard: isSet(object.includeWildcard)
        ? globalThis.Boolean(object.includeWildcard)
        : isSet(object.include_wildcard)
        ? globalThis.Boolean(object.include_wildcard)
        : false,
      certificate: isSet(object.certificate) ? Certificate.fromJSON(object.certificate) : undefined,
    };
  },

  toJSON(message: Record): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      obj.updatedAt = Math.round(message.updatedAt);
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.zoneId !== 0) {
      obj.zoneId = Math.round(message.zoneId);
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.ttl !== 0) {
      obj.ttl = Math.round(message.ttl);
    }
    if (message.addressId !== 0) {
      obj.addressId = Math.round(message.addressId);
    }
    if (message.address !== undefined) {
      obj.address = Address.toJSON(message.address);
    }
    if (message.purpose !== 0) {
      obj.purpose = recordPurposeToJSON(message.purpose);
    }
    if (message.includeWildcard !== false) {
      obj.includeWildcard = message.includeWildcard;
    }
    if (message.certificate !== undefined) {
      obj.certificate = Certificate.toJSON(message.certificate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Record>, I>>(base?: I): Record {
    return Record.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Record>, I>>(object: I): Record {
    const message = createBaseRecord();
    message.id = object.id ?? 0;
    message.createdAt = object.createdAt ?? 0;
    message.updatedAt = object.updatedAt ?? 0;
    message.token = object.token ?? "";
    message.zoneId = object.zoneId ?? 0;
    message.domain = object.domain ?? "";
    message.name = object.name ?? "";
    message.ttl = object.ttl ?? 0;
    message.addressId = object.addressId ?? 0;
    message.address = (object.address !== undefined && object.address !== null)
      ? Address.fromPartial(object.address)
      : undefined;
    message.purpose = object.purpose ?? 0;
    message.includeWildcard = object.includeWildcard ?? false;
    message.certificate = (object.certificate !== undefined && object.certificate !== null)
      ? Certificate.fromPartial(object.certificate)
      : undefined;
    return message;
  },
};

function createBaseRecordList(): RecordList {
  return { records: [] };
}

export const RecordList: MessageFns<RecordList> = {
  encode(message: RecordList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.records) {
      Record.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecordList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecordList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.records.push(Record.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RecordList {
    return {
      records: globalThis.Array.isArray(object?.records) ? object.records.map((e: any) => Record.fromJSON(e)) : [],
    };
  },

  toJSON(message: RecordList): unknown {
    const obj: any = {};
    if (message.records?.length) {
      obj.records = message.records.map((e) => Record.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RecordList>, I>>(base?: I): RecordList {
    return RecordList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecordList>, I>>(object: I): RecordList {
    const message = createBaseRecordList();
    message.records = object.records?.map((e) => Record.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRecordDelete(): RecordDelete {
  return { record: undefined, deleteFromHetzner: false };
}

export const RecordDelete: MessageFns<RecordDelete> = {
  encode(message: RecordDelete, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.record !== undefined) {
      Record.encode(message.record, writer.uint32(10).fork()).join();
    }
    if (message.deleteFromHetzner !== false) {
      writer.uint32(16).bool(message.deleteFromHetzner);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecordDelete {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecordDelete();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.record = Record.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.deleteFromHetzner = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RecordDelete {
    return {
      record: isSet(object.record) ? Record.fromJSON(object.record) : undefined,
      deleteFromHetzner: isSet(object.deleteFromHetzner)
        ? globalThis.Boolean(object.deleteFromHetzner)
        : isSet(object.delete_from_hetzner)
        ? globalThis.Boolean(object.delete_from_hetzner)
        : false,
    };
  },

  toJSON(message: RecordDelete): unknown {
    const obj: any = {};
    if (message.record !== undefined) {
      obj.record = Record.toJSON(message.record);
    }
    if (message.deleteFromHetzner !== false) {
      obj.deleteFromHetzner = message.deleteFromHetzner;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RecordDelete>, I>>(base?: I): RecordDelete {
    return RecordDelete.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecordDelete>, I>>(object: I): RecordDelete {
    const message = createBaseRecordDelete();
    message.record = (object.record !== undefined && object.record !== null)
      ? Record.fromPartial(object.record)
      : undefined;
    message.deleteFromHetzner = object.deleteFromHetzner ?? false;
    return message;
  },
};

function createBaseCertificate(): Certificate {
  return {
    id: 0,
    createdAt: 0,
    updatedAt: 0,
    recordId: 0,
    domains: "",
    status: "",
    notBefore: 0,
    notAfter: 0,
    serial: "",
    lastError: "",
  };
}

export const Certificate: MessageFns<Certificate> = {
  encode(message: Certificate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.createdAt !== 0) {
      writer.uint32(16).int64(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      writer.uint32(24).int64(message.updatedAt);
    }
    if (message.recordId !== 0) {
      writer.uint32(32).int64(message.recordId);
    }
    if (message.domains !== "") {
      writer.uint32(42).string(message.domains);
    }
    if (message.status !== "") {
      writer.uint32(50).string(message.status);
    }
    if (message.notBefore !== 0) {
      writer.uint32(56).int64(message.notBefore);
    }
    if (message.notAfter !== 0) {
      writer.uint32(64).int64(message.notAfter);
    }
    if (message.serial !== "") {
      writer.uint32(74).string(message.serial);
    }
    if (message.lastError !== "") {
      writer.uint32(82).string(message.lastError);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Certificate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCertificate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.createdAt = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.updatedAt = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.recordId = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.domains = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.notBefore = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.notAfter = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.serial = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.lastError = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Certificate {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      createdAt: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      updatedAt: isSet(object.updatedAt)
        ? globalThis.Number(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.Number(object.updated_at)
        : 0,
      recordId: isSet(object.recordId)
        ? globalThis.Number(object.recordId)
        : isSet(object.record_id)
        ? globalThis.Number(object.record_id)
        : 0,
      domains: isSet(object.domains) ? globalThis.String(object.domains) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      notBefore: isSet(object.notBefore)
        ? globalThis.Number(object.notBefore)
        : isSet(object.not_before)
        ? globalThis.Number(object.not_before)
        : 0,
      notAfter: isSet(object.notAfter)
        ? globalThis.Number(object.notAfter)
        : isSet(object.not_after)
        ? globalThis.Number(object.not_after)
        : 0,
      serial: isSet(object.serial) ? globalThis.String(object.serial) : "",
      lastError: isSet(object.lastError)
        ? globalThis.String(object.lastError)
        : isSet(object.last_error)
        ? globalThis.String(object.last_error)
        : "",
    };
  },

  toJSON(message: Certificate): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      obj.updatedAt = Math.round(message.updatedAt);
    }
    if (message.recordId !== 0) {
      obj.recordId = Math.round(message.recordId);
    }
    if (message.domains !== "") {
      obj.domains = message.domains;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.notBefore !== 0) {
      obj.notBefore = Math.round(message.notBefore);
    }
    if (message.notAfter !== 0) {
      obj.notAfter = Math.round(message.notAfter);
    }
    if (message.serial !== "") {
      obj.serial = message.serial;
    }
    if (message.lastError !== "") {
      obj.lastError = message.lastError;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Certificate>, I>>(base?: I): Certificate {
    return Certificate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Certificate>, I>>(object: I): Certificate {
    const message = createBaseCertificate();
    message.id = object.id ?? 0;
    message.createdAt = object.createdAt ?? 0;
    message.updatedAt = object.updatedAt ?? 0;
    message.recordId = object.recordId ?? 0;
    message.domains = object.domains ?? "";
    message.status = object.status ?? "";
    message.notBefore = object.notBefore ?? 0;
    message.notAfter = object.notAfter ?? 0;
    message.serial = object.serial ?? "";
    message.lastError = object.lastError ?? "";
    return message;
  },
};

function createBaseCertificateList(): CertificateList {
  return { certificates: [] };
}

export const CertificateList: MessageFns<CertificateList> = {
  encode(message: CertificateList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.certificates) {
      Certificate.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CertificateList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCertificateList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.certificates.push(Certificate.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CertificateList {
    return {
      certificates: globalThis.Array.isArray(object?.certificates)
        ? object.certificates.map((e: any) => Certificate.fromJSON(e))
        : [],
    };
  },

  toJSON(message: CertificateList): unknown {
    const obj: any = {};
    if (message.certificates?.length) {
      obj.certificates = message.certificates.map((e) => Certificate.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CertificateList>, I>>(base?: I): CertificateList {
    return CertificateList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CertificateList>, I>>(object: I): CertificateList {
    const message = createBaseCertificateList();
    message.certificates = object.certificates?.map((e) => Certificate.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTask(): Task {
  return {
    id: 0,
    createdAt: 0,
    updatedAt: 0,
    recordId: 0,
    name: "",
    triggerOn: 0,
    method: "",
    url: "",
    headers: "",
    body: "",
    enabled: false,
    lastRun: 0,
    lastStatus: "",
    lastError: "",
    includeCertificate: false,
  };
}

export const Task: MessageFns<Task> = {
  encode(message: Task, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.createdAt !== 0) {
      writer.uint32(16).int64(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      writer.uint32(24).int64(message.updatedAt);
    }
    if (message.recordId !== 0) {
      writer.uint32(32).int64(message.recordId);
    }
    if (message.name !== "") {
      writer.uint32(42).string(message.name);
    }
    if (message.triggerOn !== 0) {
      writer.uint32(48).int32(message.triggerOn);
    }
    if (message.method !== "") {
      writer.uint32(58).string(message.method);
    }
    if (message.url !== "") {
      writer.uint32(66).string(message.url);
    }
    if (message.headers !== "") {
      writer.uint32(74).string(message.headers);
    }
    if (message.body !== "") {
      writer.uint32(82).string(message.body);
    }
    if (message.enabled !== false) {
      writer.uint32(88).bool(message.enabled);
    }
    if (message.lastRun !== 0) {
      writer.uint32(96).int64(message.lastRun);
    }
    if (message.lastStatus !== "") {
      writer.uint32(106).string(message.lastStatus);
    }
    if (message.lastError !== "") {
      writer.uint32(114).string(message.lastError);
    }
    if (message.includeCertificate !== false) {
      writer.uint32(120).bool(message.includeCertificate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Task {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTask();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.createdAt = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.updatedAt = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.recordId = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.triggerOn = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.headers = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.body = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.lastRun = longToNumber(reader.int64());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.lastStatus = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.lastError = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.includeCertificate = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Task {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      createdAt: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      updatedAt: isSet(object.updatedAt)
        ? globalThis.Number(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.Number(object.updated_at)
        : 0,
      recordId: isSet(object.recordId)
        ? globalThis.Number(object.recordId)
        : isSet(object.record_id)
        ? globalThis.Number(object.record_id)
        : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      triggerOn: isSet(object.triggerOn)
        ? taskTriggerFromJSON(object.triggerOn)
        : isSet(object.trigger_on)
        ? taskTriggerFromJSON(object.trigger_on)
        : 0,
      method: isSet(object.method) ? globalThis.String(object.method) : "",
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      headers: isSet(object.headers) ? globalThis.String(object.headers) : "",
      body: isSet(object.body) ? globalThis.String(object.body) : "",
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      lastRun: isSet(object.lastRun)
        ? globalThis.Number(object.lastRun)
        : isSet(object.last_run)
        ? globalThis.Number(object.last_run)
        : 0,
      lastStatus: isSet(object.lastStatus)
        ? globalThis.String(object.lastStatus)
        : isSet(object.last_status)
        ? globalThis.String(object.last_status)
        : "",
      lastError: isSet(object.lastError)
        ? globalThis.String(object.lastError)
        : isSet(object.last_error)
        ? globalThis.String(object.last_error)
        : "",
      includeCertificate: isSet(object.includeCertificate)
        ? globalThis.Boolean(object.includeCertificate)
        : isSet(object.include_certificate)
        ? globalThis.Boolean(object.include_certificate)
        : false,
    };
  },

  toJSON(message: Task): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      obj.updatedAt = Math.round(message.updatedAt);
    }
    if (message.recordId !== 0) {
      obj.recordId = Math.round(message.recordId);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.triggerOn !== 0) {
      obj.triggerOn = taskTriggerToJSON(message.triggerOn);
    }
    if (message.method !== "") {
      obj.method = message.method;
    }
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.headers !== "") {
      obj.headers = message.headers;
    }
    if (message.body !== "") {
      obj.body = message.body;
    }
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.lastRun !== 0) {
      obj.lastRun = Math.round(message.lastRun);
    }
    if (message.lastStatus !== "") {
      obj.lastStatus = message.lastStatus;
    }
    if (message.lastError !== "") {
      obj.lastError = message.lastError;
    }
    if (message.includeCertificate !== false) {
      obj.includeCertificate = message.includeCertificate;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Task>, I>>(base?: I): Task {
    return Task.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Task>, I>>(object: I): Task {
    const message = createBaseTask();
    message.id = object.id ?? 0;
    message.createdAt = object.createdAt ?? 0;
    message.updatedAt = object.updatedAt ?? 0;
    message.recordId = object.recordId ?? 0;
    message.name = object.name ?? "";
    message.triggerOn = object.triggerOn ?? 0;
    message.method = object.method ?? "";
    message.url = object.url ?? "";
    message.headers = object.headers ?? "";
    message.body = object.body ?? "";
    message.enabled = object.enabled ?? false;
    message.lastRun = object.lastRun ?? 0;
    message.lastStatus = object.lastStatus ?? "";
    message.lastError = object.lastError ?? "";
    message.includeCertificate = object.includeCertificate ?? false;
    return message;
  },
};

function createBaseTaskList(): TaskList {
  return { tasks: [] };
}

export const TaskList: MessageFns<TaskList> = {
  encode(message: TaskList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tasks) {
      Task.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tasks.push(Task.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskList {
    return { tasks: globalThis.Array.isArray(object?.tasks) ? object.tasks.map((e: any) => Task.fromJSON(e)) : [] };
  },

  toJSON(message: TaskList): unknown {
    const obj: any = {};
    if (message.tasks?.length) {
      obj.tasks = message.tasks.map((e) => Task.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TaskList>, I>>(base?: I): TaskList {
    return TaskList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TaskList>, I>>(object: I): TaskList {
    const message = createBaseTaskList();
    message.tasks = object.tasks?.map((e) => Task.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTaskDelete(): TaskDelete {
  return { id: 0 };
}

export const TaskDelete: MessageFns<TaskDelete> = {
  encode(message: TaskDelete, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskDelete {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskDelete();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskDelete {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: TaskDelete): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TaskDelete>, I>>(base?: I): TaskDelete {
    return TaskDelete.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TaskDelete>, I>>(object: I): TaskDelete {
    const message = createBaseTaskDelete();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseTaskResult(): TaskResult {
  return { status: "", error: "" };
}

export const TaskResult: MessageFns<TaskResult> = {
  encode(message: TaskResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.error !== "") {
      writer.uint32(18).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskResult {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      error: isSet(object.error) ? globalThis.String(object.error) : "",
    };
  },

  toJSON(message: TaskResult): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TaskResult>, I>>(base?: I): TaskResult {
    return TaskResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TaskResult>, I>>(object: I): TaskResult {
    const message = createBaseTaskResult();
    message.status = object.status ?? "";
    message.error = object.error ?? "";
    return message;
  },
};

function createBaseZone(): Zone {
  return { id: 0, name: "", recordCount: 0 };
}

export const Zone: MessageFns<Zone> = {
  encode(message: Zone, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.recordCount !== 0) {
      writer.uint32(24).int64(message.recordCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Zone {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseZone();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.recordCount = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Zone {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      recordCount: isSet(object.recordCount)
        ? globalThis.Number(object.recordCount)
        : isSet(object.record_count)
        ? globalThis.Number(object.record_count)
        : 0,
    };
  },

  toJSON(message: Zone): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.recordCount !== 0) {
      obj.recordCount = Math.round(message.recordCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Zone>, I>>(base?: I): Zone {
    return Zone.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Zone>, I>>(object: I): Zone {
    const message = createBaseZone();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.recordCount = object.recordCount ?? 0;
    return message;
  },
};

function createBaseZoneList(): ZoneList {
  return { zones: [] };
}

export const ZoneList: MessageFns<ZoneList> = {
  encode(message: ZoneList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.zones) {
      Zone.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ZoneList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseZoneList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.zones.push(Zone.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ZoneList {
    return { zones: globalThis.Array.isArray(object?.zones) ? object.zones.map((e: any) => Zone.fromJSON(e)) : [] };
  },

  toJSON(message: ZoneList): unknown {
    const obj: any = {};
    if (message.zones?.length) {
      obj.zones = message.zones.map((e) => Zone.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ZoneList>, I>>(base?: I): ZoneList {
    return ZoneList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ZoneList>, I>>(object: I): ZoneList {
    const message = createBaseZoneList();
    message.zones = object.zones?.map((e) => Zone.fromPartial(e)) || [];
    return message;
  },
};

function createBaseResolution(): Resolution {
  return { server: "", addresses: [], responseTime: 0, error: "" };
}

export const Resolution: MessageFns<Resolution> = {
  encode(message: Resolution, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.server !== "") {
      writer.uint32(10).string(message.server);
    }
    for (const v of message.addresses) {
      writer.uint32(18).string(v!);
    }
    if (message.responseTime !== 0) {
      writer.uint32(24).int64(message.responseTime);
    }
    if (message.error !== "") {
      writer.uint32(34).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Resolution {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResolution();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.server = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.addresses.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.responseTime = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Resolution {
    return {
      server: isSet(object.server) ? globalThis.String(object.server) : "",
      addresses: globalThis.Array.isArray(object?.addresses)
        ? object.addresses.map((e: any) => globalThis.String(e))
        : [],
      responseTime: isSet(object.responseTime)
        ? globalThis.Number(object.responseTime)
        : isSet(object.response_time)
        ? globalThis.Number(object.response_time)
        : 0,
      error: isSet(object.error) ? globalThis.String(object.error) : "",
    };
  },

  toJSON(message: Resolution): unknown {
    const obj: any = {};
    if (message.server !== "") {
      obj.server = message.server;
    }
    if (message.addresses?.length) {
      obj.addresses = message.addresses;
    }
    if (message.responseTime !== 0) {
      obj.responseTime = Math.round(message.responseTime);
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Resolution>, I>>(base?: I): Resolution {
    return Resolution.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Resolution>, I>>(object: I): Resolution {
    const message = createBaseResolution();
    message.server = object.server ?? "";
    message.addresses = object.addresses?.map((e) => e) || [];
    message.responseTime = object.responseTime ?? 0;
    message.error = object.error ?? "";
    return message;
  },
};

function createBaseResolutionResult(): ResolutionResult {
  return { resolutions: [] };
}

export const ResolutionResult: MessageFns<ResolutionResult> = {
  encode(message: ResolutionResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.resolutions) {
      Resolution.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResolutionResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResolutionResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resolutions.push(Resolution.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResolutionResult {
    return {
      resolutions: globalThis.Array.isArray(object?.resolutions)
        ? object.resolutions.map((e: any) => Resolution.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ResolutionResult): unknown {
    const obj: any = {};
    if (message.resolutions?.length) {
      obj.resolutions = message.resolutions.map((e) => Resolution.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResolutionResult>, I>>(base?: I): ResolutionResult {
    return ResolutionResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResolutionResult>, I>>(object: I): ResolutionResult {
    const message = createBaseResolutionResult();
    message.resolutions = object.resolutions?.map((e) => Resolution.fromPartial(e)) || [];
    return message;
  },
};

function createBaseConfiguration(): Configuration {
  return {
    logLevel: 0,
    refreshCron: "",
    dnsServers: [],
    ipv4Resolvers: [],
    ipv6Resolvers: [],
    notificationsEnabled: false,
    notificationsOnSuccess: false,
    notificationsRecipients: [],
    notificationsCooldownMinutes: 0,
    notificationsSubjectPrefix: "",
    acmeEnabled: false,
    acmeEmail: "",
    acmeStaging: false,
    acmeRenewBeforeDays: 0,
  };
}

export const Configuration: MessageFns<Configuration> = {
  encode(message: Configuration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.logLevel !== 0) {
      writer.uint32(8).int32(message.logLevel);
    }
    if (message.refreshCron !== "") {
      writer.uint32(18).string(message.refreshCron);
    }
    for (const v of message.dnsServers) {
      writer.uint32(26).string(v!);
    }
    for (const v of message.ipv4Resolvers) {
      writer.uint32(34).string(v!);
    }
    for (const v of message.ipv6Resolvers) {
      writer.uint32(42).string(v!);
    }
    if (message.notificationsEnabled !== false) {
      writer.uint32(48).bool(message.notificationsEnabled);
    }
    if (message.notificationsOnSuccess !== false) {
      writer.uint32(56).bool(message.notificationsOnSuccess);
    }
    for (const v of message.notificationsRecipients) {
      writer.uint32(66).string(v!);
    }
    if (message.notificationsCooldownMinutes !== 0) {
      writer.uint32(72).int32(message.notificationsCooldownMinutes);
    }
    if (message.notificationsSubjectPrefix !== "") {
      writer.uint32(82).string(message.notificationsSubjectPrefix);
    }
    if (message.acmeEnabled !== false) {
      writer.uint32(88).bool(message.acmeEnabled);
    }
    if (message.acmeEmail !== "") {
      writer.uint32(98).string(message.acmeEmail);
    }
    if (message.acmeStaging !== false) {
      writer.uint32(104).bool(message.acmeStaging);
    }
    if (message.acmeRenewBeforeDays !== 0) {
      writer.uint32(112).int32(message.acmeRenewBeforeDays);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Configuration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfiguration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.logLevel = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.refreshCron = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.dnsServers.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ipv4Resolvers.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.ipv6Resolvers.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.notificationsEnabled = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.notificationsOnSuccess = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.notificationsRecipients.push(reader.string());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.notificationsCooldownMinutes = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.notificationsSubjectPrefix = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.acmeEnabled = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.acmeEmail = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.acmeStaging = reader.bool();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.acmeRenewBeforeDays = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Configuration {
    return {
      logLevel: isSet(object.logLevel)
        ? globalThis.Number(object.logLevel)
        : isSet(object.log_level)
        ? globalThis.Number(object.log_level)
        : 0,
      refreshCron: isSet(object.refreshCron)
        ? globalThis.String(object.refreshCron)
        : isSet(object.refresh_cron)
        ? globalThis.String(object.refresh_cron)
        : "",
      dnsServers: globalThis.Array.isArray(object?.dnsServers)
        ? object.dnsServers.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.dns_servers)
        ? object.dns_servers.map((e: any) => globalThis.String(e))
        : [],
      ipv4Resolvers: globalThis.Array.isArray(object?.ipv4Resolvers)
        ? object.ipv4Resolvers.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.ipv4_resolvers)
        ? object.ipv4_resolvers.map((e: any) => globalThis.String(e))
        : [],
      ipv6Resolvers: globalThis.Array.isArray(object?.ipv6Resolvers)
        ? object.ipv6Resolvers.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.ipv6_resolvers)
        ? object.ipv6_resolvers.map((e: any) => globalThis.String(e))
        : [],
      notificationsEnabled: isSet(object.notificationsEnabled)
        ? globalThis.Boolean(object.notificationsEnabled)
        : isSet(object.notifications_enabled)
        ? globalThis.Boolean(object.notifications_enabled)
        : false,
      notificationsOnSuccess: isSet(object.notificationsOnSuccess)
        ? globalThis.Boolean(object.notificationsOnSuccess)
        : isSet(object.notifications_on_success)
        ? globalThis.Boolean(object.notifications_on_success)
        : false,
      notificationsRecipients: globalThis.Array.isArray(object?.notificationsRecipients)
        ? object.notificationsRecipients.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.notifications_recipients)
        ? object.notifications_recipients.map((e: any) => globalThis.String(e))
        : [],
      notificationsCooldownMinutes: isSet(object.notificationsCooldownMinutes)
        ? globalThis.Number(object.notificationsCooldownMinutes)
        : isSet(object.notifications_cooldown_minutes)
        ? globalThis.Number(object.notifications_cooldown_minutes)
        : 0,
      notificationsSubjectPrefix: isSet(object.notificationsSubjectPrefix)
        ? globalThis.String(object.notificationsSubjectPrefix)
        : isSet(object.notifications_subject_prefix)
        ? globalThis.String(object.notifications_subject_prefix)
        : "",
      acmeEnabled: isSet(object.acmeEnabled)
        ? globalThis.Boolean(object.acmeEnabled)
        : isSet(object.acme_enabled)
        ? globalThis.Boolean(object.acme_enabled)
        : false,
      acmeEmail: isSet(object.acmeEmail)
        ? globalThis.String(object.acmeEmail)
        : isSet(object.acme_email)
        ? globalThis.String(object.acme_email)
        : "",
      acmeStaging: isSet(object.acmeStaging)
        ? globalThis.Boolean(object.acmeStaging)
        : isSet(object.acme_staging)
        ? globalThis.Boolean(object.acme_staging)
        : false,
      acmeRenewBeforeDays: isSet(object.acmeRenewBeforeDays)
        ? globalThis.Number(object.acmeRenewBeforeDays)
        : isSet(object.acme_renew_before_days)
        ? globalThis.Number(object.acme_renew_before_days)
        : 0,
    };
  },

  toJSON(message: Configuration): unknown {
    const obj: any = {};
    if (message.logLevel !== 0) {
      obj.logLevel = Math.round(message.logLevel);
    }
    if (message.refreshCron !== "") {
      obj.refreshCron = message.refreshCron;
    }
    if (message.dnsServers?.length) {
      obj.dnsServers = message.dnsServers;
    }
    if (message.ipv4Resolvers?.length) {
      obj.ipv4Resolvers = message.ipv4Resolvers;
    }
    if (message.ipv6Resolvers?.length) {
      obj.ipv6Resolvers = message.ipv6Resolvers;
    }
    if (message.notificationsEnabled !== false) {
      obj.notificationsEnabled = message.notificationsEnabled;
    }
    if (message.notificationsOnSuccess !== false) {
      obj.notificationsOnSuccess = message.notificationsOnSuccess;
    }
    if (message.notificationsRecipients?.length) {
      obj.notificationsRecipients = message.notificationsRecipients;
    }
    if (message.notificationsCooldownMinutes !== 0) {
      obj.notificationsCooldownMinutes = Math.round(message.notificationsCooldownMinutes);
    }
    if (message.notificationsSubjectPrefix !== "") {
      obj.notificationsSubjectPrefix = message.notificationsSubjectPrefix;
    }
    if (message.acmeEnabled !== false) {
      obj.acmeEnabled = message.acmeEnabled;
    }
    if (message.acmeEmail !== "") {
      obj.acmeEmail = message.acmeEmail;
    }
    if (message.acmeStaging !== false) {
      obj.acmeStaging = message.acmeStaging;
    }
    if (message.acmeRenewBeforeDays !== 0) {
      obj.acmeRenewBeforeDays = Math.round(message.acmeRenewBeforeDays);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Configuration>, I>>(base?: I): Configuration {
    return Configuration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Configuration>, I>>(object: I): Configuration {
    const message = createBaseConfiguration();
    message.logLevel = object.logLevel ?? 0;
    message.refreshCron = object.refreshCron ?? "";
    message.dnsServers = object.dnsServers?.map((e) => e) || [];
    message.ipv4Resolvers = object.ipv4Resolvers?.map((e) => e) || [];
    message.ipv6Resolvers = object.ipv6Resolvers?.map((e) => e) || [];
    message.notificationsEnabled = object.notificationsEnabled ?? false;
    message.notificationsOnSuccess = object.notificationsOnSuccess ?? false;
    message.notificationsRecipients = object.notificationsRecipients?.map((e) => e) || [];
    message.notificationsCooldownMinutes = object.notificationsCooldownMinutes ?? 0;
    message.notificationsSubjectPrefix = object.notificationsSubjectPrefix ?? "";
    message.acmeEnabled = object.acmeEnabled ?? false;
    message.acmeEmail = object.acmeEmail ?? "";
    message.acmeStaging = object.acmeStaging ?? false;
    message.acmeRenewBeforeDays = object.acmeRenewBeforeDays ?? 0;
    return message;
  },
};

function createBaseLogEntry(): LogEntry {
  return { timestamp: 0, level: 0, message: "" };
}

export const LogEntry: MessageFns<LogEntry> = {
  encode(message: LogEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestamp !== 0) {
      writer.uint32(8).int64(message.timestamp);
    }
    if (message.level !== 0) {
      writer.uint32(16).int32(message.level);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.level = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogEntry {
    return {
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: LogEntry): unknown {
    const obj: any = {};
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogEntry>, I>>(base?: I): LogEntry {
    return LogEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogEntry>, I>>(object: I): LogEntry {
    const message = createBaseLogEntry();
    message.timestamp = object.timestamp ?? 0;
    message.level = object.level ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

/** HDNS is the main service for HDNS. */
export type HDNSDefinition = typeof HDNSDefinition;
export const HDNSDefinition = {
  name: "HDNS",
  fullName: "service.HDNS",
  methods: {
    /** GetZones returns all zones. */
    getZones: {
      name: "GetZones",
      requestType: ZoneRequest as typeof ZoneRequest,
      requestStream: false,
      responseType: ZoneList as typeof ZoneList,
      responseStream: false,
      options: {},
    },
    /** GetRecords returns all records. */
    getRecords: {
      name: "GetRecords",
      requestType: Request as typeof Request,
      requestStream: false,
      responseType: RecordList as typeof RecordList,
      responseStream: false,
      options: {},
    },
    /** UpsertRecord creates or updates a record. */
    upsertRecord: {
      name: "UpsertRecord",
      requestType: Record as typeof Record,
      requestStream: false,
      responseType: Record as typeof Record,
      responseStream: false,
      options: {},
    },
    /** DeleteRecord deletes a record. */
    deleteRecord: {
      name: "DeleteRecord",
      requestType: RecordDelete as typeof RecordDelete,
      requestStream: false,
      responseType: Empty as typeof Empty,
      responseStream: false,
      options: {},
    },
    /** RefreshRecord refreshes the record's address. */
    refreshRecord: {
      name: "RefreshRecord",
      requestType: Record as typeof Record,
      requestStream: false,
      responseType: Record as typeof Record,
      responseStream: false,
      options: {},
    },
    /** FetchHetznerRecord returns the A record currently defined in Hetzner for this record. */
    fetchHetznerRecord: {
      name: "FetchHetznerRecord",
      requestType: Record as typeof Record,
      requestStream: false,
      responseType: Address as typeof Address,
      responseStream: false,
      options: {},
    },
    /** ResolveRecord resolves the record's domain. */
    resolveRecord: {
      name: "ResolveRecord",
      requestType: Record as typeof Record,
      requestStream: false,
      responseType: ResolutionResult as typeof ResolutionResult,
      responseStream: false,
      options: {},
    },
    /** StreamResolveRecord streams the resolution results for the record. */
    streamResolveRecord: {
      name: "StreamResolveRecord",
      requestType: Record as typeof Record,
      requestStream: false,
      responseType: Resolution as typeof Resolution,
      responseStream: true,
      options: {},
    },
    /** StreamAddress streams the current address. */
    streamAddress: {
      name: "StreamAddress",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: Address as typeof Address,
      responseStream: true,
      options: {},
    },
    /** GetAddress returns the current address. */
    getAddress: {
      name: "GetAddress",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: Address as typeof Address,
      responseStream: false,
      options: {},
    },
    /** GetAddressHistory returns the address history. */
    getAddressHistory: {
      name: "GetAddressHistory",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: AddressHistory as typeof AddressHistory,
      responseStream: false,
      options: {},
    },
    /** RefreshAddress refreshes the current address. */
    refreshAddress: {
      name: "RefreshAddress",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: Address as typeof Address,
      responseStream: false,
      options: {},
    },
    /** GetCertificates returns all certificates. */
    getCertificates: {
      name: "GetCertificates",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: CertificateList as typeof CertificateList,
      responseStream: false,
      options: {},
    },
    /** IssueCertificate issues or re-issues the certificate for a record. */
    issueCertificate: {
      name: "IssueCertificate",
      requestType: Record as typeof Record,
      requestStream: false,
      responseType: Certificate as typeof Certificate,
      responseStream: false,
      options: {},
    },
    /** GetTasks returns all renewal tasks. */
    getTasks: {
      name: "GetTasks",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: TaskList as typeof TaskList,
      responseStream: false,
      options: {},
    },
    /** UpsertTask creates or updates a renewal task. */
    upsertTask: {
      name: "UpsertTask",
      requestType: Task as typeof Task,
      requestStream: false,
      responseType: Task as typeof Task,
      responseStream: false,
      options: {},
    },
    /** DeleteTask deletes a renewal task. */
    deleteTask: {
      name: "DeleteTask",
      requestType: TaskDelete as typeof TaskDelete,
      requestStream: false,
      responseType: Empty as typeof Empty,
      responseStream: false,
      options: {},
    },
    /** TestTask executes a renewal task immediately and returns the result. */
    testTask: {
      name: "TestTask",
      requestType: Task as typeof Task,
      requestStream: false,
      responseType: TaskResult as typeof TaskResult,
      responseStream: false,
      options: {},
    },
    /** GetConfig returns the current configuration. */
    getConfig: {
      name: "GetConfig",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: Configuration as typeof Configuration,
      responseStream: false,
      options: {},
    },
    /** UpdateConfig updates the current configuration. */
    updateConfig: {
      name: "UpdateConfig",
      requestType: Configuration as typeof Configuration,
      requestStream: false,
      responseType: Configuration as typeof Configuration,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
