// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: api.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export interface Empty {
}

export interface Request {
  token: string;
}

/** Address represents an IP address. */
export interface Address {
  id: number;
  createdAt: number;
  updatedAt: number;
  ipv4: string;
  ipv6: string;
  current: boolean;
}

export interface AddressHistory {
  addresses: Address[];
}

/** Record represents a DNS record. */
export interface Record {
  id: number;
  createdAt: number;
  updatedAt: number;
  token: string;
  zoneId: number;
  domain: string;
  name: string;
  ttl: number;
  addressId: number;
  address: Address | undefined;
}

export interface RecordList {
  records: Record[];
}

export interface RecordDelete {
  record: Record | undefined;
  deleteFromHetzner: boolean;
}

export interface Zone {
  id: number;
  name: string;
  recordCount: number;
}

export interface ZoneList {
  zones: Zone[];
}

export interface Resolution {
  server: string;
  addresses: string[];
  responseTime: number;
  error: string;
}

export interface ResolutionResult {
  resolutions: Resolution[];
}

export interface Configuration {
  logLevel: number;
  webPort: number;
  certificatePath: string;
  keyPath: string;
  refreshCron: string;
  dnsServers: string[];
  ipv4Resolvers: string[];
  ipv6Resolvers: string[];
  database: string;
}

export interface LogEntry {
  timestamp: number;
  level: number;
  message: string;
}

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

function createBaseRequest(): Request {
  return { token: "" };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseAddress(): Address {
  return { id: 0, createdAt: 0, updatedAt: 0, ipv4: "", ipv6: "", current: false };
}

export const Address: MessageFns<Address> = {
  encode(message: Address, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.createdAt !== 0) {
      writer.uint32(16).int64(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      writer.uint32(24).int64(message.updatedAt);
    }
    if (message.ipv4 !== "") {
      writer.uint32(34).string(message.ipv4);
    }
    if (message.ipv6 !== "") {
      writer.uint32(42).string(message.ipv6);
    }
    if (message.current !== false) {
      writer.uint32(48).bool(message.current);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Address {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.createdAt = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.updatedAt = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ipv4 = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.ipv6 = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.current = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Address {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      createdAt: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      updatedAt: isSet(object.updatedAt)
        ? globalThis.Number(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.Number(object.updated_at)
        : 0,
      ipv4: isSet(object.ipv4) ? globalThis.String(object.ipv4) : "",
      ipv6: isSet(object.ipv6) ? globalThis.String(object.ipv6) : "",
      current: isSet(object.current) ? globalThis.Boolean(object.current) : false,
    };
  },

  toJSON(message: Address): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      obj.updatedAt = Math.round(message.updatedAt);
    }
    if (message.ipv4 !== "") {
      obj.ipv4 = message.ipv4;
    }
    if (message.ipv6 !== "") {
      obj.ipv6 = message.ipv6;
    }
    if (message.current !== false) {
      obj.current = message.current;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Address>, I>>(base?: I): Address {
    return Address.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Address>, I>>(object: I): Address {
    const message = createBaseAddress();
    message.id = object.id ?? 0;
    message.createdAt = object.createdAt ?? 0;
    message.updatedAt = object.updatedAt ?? 0;
    message.ipv4 = object.ipv4 ?? "";
    message.ipv6 = object.ipv6 ?? "";
    message.current = object.current ?? false;
    return message;
  },
};

function createBaseAddressHistory(): AddressHistory {
  return { addresses: [] };
}

export const AddressHistory: MessageFns<AddressHistory> = {
  encode(message: AddressHistory, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.addresses) {
      Address.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddressHistory {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddressHistory();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.addresses.push(Address.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddressHistory {
    return {
      addresses: globalThis.Array.isArray(object?.addresses)
        ? object.addresses.map((e: any) => Address.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AddressHistory): unknown {
    const obj: any = {};
    if (message.addresses?.length) {
      obj.addresses = message.addresses.map((e) => Address.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddressHistory>, I>>(base?: I): AddressHistory {
    return AddressHistory.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddressHistory>, I>>(object: I): AddressHistory {
    const message = createBaseAddressHistory();
    message.addresses = object.addresses?.map((e) => Address.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRecord(): Record {
  return {
    id: 0,
    createdAt: 0,
    updatedAt: 0,
    token: "",
    zoneId: 0,
    domain: "",
    name: "",
    ttl: 0,
    addressId: 0,
    address: undefined,
  };
}

export const Record: MessageFns<Record> = {
  encode(message: Record, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.createdAt !== 0) {
      writer.uint32(16).int64(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      writer.uint32(24).int64(message.updatedAt);
    }
    if (message.token !== "") {
      writer.uint32(34).string(message.token);
    }
    if (message.zoneId !== 0) {
      writer.uint32(40).int64(message.zoneId);
    }
    if (message.domain !== "") {
      writer.uint32(50).string(message.domain);
    }
    if (message.name !== "") {
      writer.uint32(58).string(message.name);
    }
    if (message.ttl !== 0) {
      writer.uint32(64).uint32(message.ttl);
    }
    if (message.addressId !== 0) {
      writer.uint32(72).int64(message.addressId);
    }
    if (message.address !== undefined) {
      Address.encode(message.address, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Record {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.createdAt = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.updatedAt = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.zoneId = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.ttl = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.addressId = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.address = Address.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Record {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      createdAt: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      updatedAt: isSet(object.updatedAt)
        ? globalThis.Number(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.Number(object.updated_at)
        : 0,
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      zoneId: isSet(object.zoneId)
        ? globalThis.Number(object.zoneId)
        : isSet(object.zone_id)
        ? globalThis.Number(object.zone_id)
        : 0,
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      ttl: isSet(object.ttl) ? globalThis.Number(object.ttl) : 0,
      addressId: isSet(object.addressId)
        ? globalThis.Number(object.addressId)
        : isSet(object.address_id)
        ? globalThis.Number(object.address_id)
        : 0,
      address: isSet(object.address) ? Address.fromJSON(object.address) : undefined,
    };
  },

  toJSON(message: Record): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      obj.updatedAt = Math.round(message.updatedAt);
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.zoneId !== 0) {
      obj.zoneId = Math.round(message.zoneId);
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.ttl !== 0) {
      obj.ttl = Math.round(message.ttl);
    }
    if (message.addressId !== 0) {
      obj.addressId = Math.round(message.addressId);
    }
    if (message.address !== undefined) {
      obj.address = Address.toJSON(message.address);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Record>, I>>(base?: I): Record {
    return Record.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Record>, I>>(object: I): Record {
    const message = createBaseRecord();
    message.id = object.id ?? 0;
    message.createdAt = object.createdAt ?? 0;
    message.updatedAt = object.updatedAt ?? 0;
    message.token = object.token ?? "";
    message.zoneId = object.zoneId ?? 0;
    message.domain = object.domain ?? "";
    message.name = object.name ?? "";
    message.ttl = object.ttl ?? 0;
    message.addressId = object.addressId ?? 0;
    message.address = (object.address !== undefined && object.address !== null)
      ? Address.fromPartial(object.address)
      : undefined;
    return message;
  },
};

function createBaseRecordList(): RecordList {
  return { records: [] };
}

export const RecordList: MessageFns<RecordList> = {
  encode(message: RecordList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.records) {
      Record.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecordList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecordList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.records.push(Record.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RecordList {
    return {
      records: globalThis.Array.isArray(object?.records) ? object.records.map((e: any) => Record.fromJSON(e)) : [],
    };
  },

  toJSON(message: RecordList): unknown {
    const obj: any = {};
    if (message.records?.length) {
      obj.records = message.records.map((e) => Record.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RecordList>, I>>(base?: I): RecordList {
    return RecordList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecordList>, I>>(object: I): RecordList {
    const message = createBaseRecordList();
    message.records = object.records?.map((e) => Record.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRecordDelete(): RecordDelete {
  return { record: undefined, deleteFromHetzner: false };
}

export const RecordDelete: MessageFns<RecordDelete> = {
  encode(message: RecordDelete, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.record !== undefined) {
      Record.encode(message.record, writer.uint32(10).fork()).join();
    }
    if (message.deleteFromHetzner !== false) {
      writer.uint32(16).bool(message.deleteFromHetzner);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecordDelete {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecordDelete();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.record = Record.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.deleteFromHetzner = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RecordDelete {
    return {
      record: isSet(object.record) ? Record.fromJSON(object.record) : undefined,
      deleteFromHetzner: isSet(object.deleteFromHetzner)
        ? globalThis.Boolean(object.deleteFromHetzner)
        : isSet(object.delete_from_hetzner)
        ? globalThis.Boolean(object.delete_from_hetzner)
        : false,
    };
  },

  toJSON(message: RecordDelete): unknown {
    const obj: any = {};
    if (message.record !== undefined) {
      obj.record = Record.toJSON(message.record);
    }
    if (message.deleteFromHetzner !== false) {
      obj.deleteFromHetzner = message.deleteFromHetzner;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RecordDelete>, I>>(base?: I): RecordDelete {
    return RecordDelete.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecordDelete>, I>>(object: I): RecordDelete {
    const message = createBaseRecordDelete();
    message.record = (object.record !== undefined && object.record !== null)
      ? Record.fromPartial(object.record)
      : undefined;
    message.deleteFromHetzner = object.deleteFromHetzner ?? false;
    return message;
  },
};

function createBaseZone(): Zone {
  return { id: 0, name: "", recordCount: 0 };
}

export const Zone: MessageFns<Zone> = {
  encode(message: Zone, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.recordCount !== 0) {
      writer.uint32(24).int64(message.recordCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Zone {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseZone();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.recordCount = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Zone {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      recordCount: isSet(object.recordCount)
        ? globalThis.Number(object.recordCount)
        : isSet(object.record_count)
        ? globalThis.Number(object.record_count)
        : 0,
    };
  },

  toJSON(message: Zone): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.recordCount !== 0) {
      obj.recordCount = Math.round(message.recordCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Zone>, I>>(base?: I): Zone {
    return Zone.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Zone>, I>>(object: I): Zone {
    const message = createBaseZone();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.recordCount = object.recordCount ?? 0;
    return message;
  },
};

function createBaseZoneList(): ZoneList {
  return { zones: [] };
}

export const ZoneList: MessageFns<ZoneList> = {
  encode(message: ZoneList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.zones) {
      Zone.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ZoneList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseZoneList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.zones.push(Zone.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ZoneList {
    return { zones: globalThis.Array.isArray(object?.zones) ? object.zones.map((e: any) => Zone.fromJSON(e)) : [] };
  },

  toJSON(message: ZoneList): unknown {
    const obj: any = {};
    if (message.zones?.length) {
      obj.zones = message.zones.map((e) => Zone.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ZoneList>, I>>(base?: I): ZoneList {
    return ZoneList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ZoneList>, I>>(object: I): ZoneList {
    const message = createBaseZoneList();
    message.zones = object.zones?.map((e) => Zone.fromPartial(e)) || [];
    return message;
  },
};

function createBaseResolution(): Resolution {
  return { server: "", addresses: [], responseTime: 0, error: "" };
}

export const Resolution: MessageFns<Resolution> = {
  encode(message: Resolution, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.server !== "") {
      writer.uint32(10).string(message.server);
    }
    for (const v of message.addresses) {
      writer.uint32(18).string(v!);
    }
    if (message.responseTime !== 0) {
      writer.uint32(24).int64(message.responseTime);
    }
    if (message.error !== "") {
      writer.uint32(34).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Resolution {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResolution();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.server = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.addresses.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.responseTime = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Resolution {
    return {
      server: isSet(object.server) ? globalThis.String(object.server) : "",
      addresses: globalThis.Array.isArray(object?.addresses)
        ? object.addresses.map((e: any) => globalThis.String(e))
        : [],
      responseTime: isSet(object.responseTime)
        ? globalThis.Number(object.responseTime)
        : isSet(object.response_time)
        ? globalThis.Number(object.response_time)
        : 0,
      error: isSet(object.error) ? globalThis.String(object.error) : "",
    };
  },

  toJSON(message: Resolution): unknown {
    const obj: any = {};
    if (message.server !== "") {
      obj.server = message.server;
    }
    if (message.addresses?.length) {
      obj.addresses = message.addresses;
    }
    if (message.responseTime !== 0) {
      obj.responseTime = Math.round(message.responseTime);
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Resolution>, I>>(base?: I): Resolution {
    return Resolution.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Resolution>, I>>(object: I): Resolution {
    const message = createBaseResolution();
    message.server = object.server ?? "";
    message.addresses = object.addresses?.map((e) => e) || [];
    message.responseTime = object.responseTime ?? 0;
    message.error = object.error ?? "";
    return message;
  },
};

function createBaseResolutionResult(): ResolutionResult {
  return { resolutions: [] };
}

export const ResolutionResult: MessageFns<ResolutionResult> = {
  encode(message: ResolutionResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.resolutions) {
      Resolution.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResolutionResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResolutionResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.resolutions.push(Resolution.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResolutionResult {
    return {
      resolutions: globalThis.Array.isArray(object?.resolutions)
        ? object.resolutions.map((e: any) => Resolution.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ResolutionResult): unknown {
    const obj: any = {};
    if (message.resolutions?.length) {
      obj.resolutions = message.resolutions.map((e) => Resolution.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResolutionResult>, I>>(base?: I): ResolutionResult {
    return ResolutionResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResolutionResult>, I>>(object: I): ResolutionResult {
    const message = createBaseResolutionResult();
    message.resolutions = object.resolutions?.map((e) => Resolution.fromPartial(e)) || [];
    return message;
  },
};

function createBaseConfiguration(): Configuration {
  return {
    logLevel: 0,
    webPort: 0,
    certificatePath: "",
    keyPath: "",
    refreshCron: "",
    dnsServers: [],
    ipv4Resolvers: [],
    ipv6Resolvers: [],
    database: "",
  };
}

export const Configuration: MessageFns<Configuration> = {
  encode(message: Configuration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.logLevel !== 0) {
      writer.uint32(8).int32(message.logLevel);
    }
    if (message.webPort !== 0) {
      writer.uint32(16).int32(message.webPort);
    }
    if (message.certificatePath !== "") {
      writer.uint32(26).string(message.certificatePath);
    }
    if (message.keyPath !== "") {
      writer.uint32(34).string(message.keyPath);
    }
    if (message.refreshCron !== "") {
      writer.uint32(42).string(message.refreshCron);
    }
    for (const v of message.dnsServers) {
      writer.uint32(50).string(v!);
    }
    for (const v of message.ipv4Resolvers) {
      writer.uint32(58).string(v!);
    }
    for (const v of message.ipv6Resolvers) {
      writer.uint32(66).string(v!);
    }
    if (message.database !== "") {
      writer.uint32(74).string(message.database);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Configuration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfiguration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.logLevel = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.webPort = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.certificatePath = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.keyPath = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.refreshCron = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.dnsServers.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.ipv4Resolvers.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.ipv6Resolvers.push(reader.string());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.database = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Configuration {
    return {
      logLevel: isSet(object.logLevel)
        ? globalThis.Number(object.logLevel)
        : isSet(object.log_level)
        ? globalThis.Number(object.log_level)
        : 0,
      webPort: isSet(object.webPort)
        ? globalThis.Number(object.webPort)
        : isSet(object.web_port)
        ? globalThis.Number(object.web_port)
        : 0,
      certificatePath: isSet(object.certificatePath)
        ? globalThis.String(object.certificatePath)
        : isSet(object.certificate_path)
        ? globalThis.String(object.certificate_path)
        : "",
      keyPath: isSet(object.keyPath)
        ? globalThis.String(object.keyPath)
        : isSet(object.key_path)
        ? globalThis.String(object.key_path)
        : "",
      refreshCron: isSet(object.refreshCron)
        ? globalThis.String(object.refreshCron)
        : isSet(object.refresh_cron)
        ? globalThis.String(object.refresh_cron)
        : "",
      dnsServers: globalThis.Array.isArray(object?.dnsServers)
        ? object.dnsServers.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.dns_servers)
        ? object.dns_servers.map((e: any) => globalThis.String(e))
        : [],
      ipv4Resolvers: globalThis.Array.isArray(object?.ipv4Resolvers)
        ? object.ipv4Resolvers.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.ipv4_resolvers)
        ? object.ipv4_resolvers.map((e: any) => globalThis.String(e))
        : [],
      ipv6Resolvers: globalThis.Array.isArray(object?.ipv6Resolvers)
        ? object.ipv6Resolvers.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.ipv6_resolvers)
        ? object.ipv6_resolvers.map((e: any) => globalThis.String(e))
        : [],
      database: isSet(object.database) ? globalThis.String(object.database) : "",
    };
  },

  toJSON(message: Configuration): unknown {
    const obj: any = {};
    if (message.logLevel !== 0) {
      obj.logLevel = Math.round(message.logLevel);
    }
    if (message.webPort !== 0) {
      obj.webPort = Math.round(message.webPort);
    }
    if (message.certificatePath !== "") {
      obj.certificatePath = message.certificatePath;
    }
    if (message.keyPath !== "") {
      obj.keyPath = message.keyPath;
    }
    if (message.refreshCron !== "") {
      obj.refreshCron = message.refreshCron;
    }
    if (message.dnsServers?.length) {
      obj.dnsServers = message.dnsServers;
    }
    if (message.ipv4Resolvers?.length) {
      obj.ipv4Resolvers = message.ipv4Resolvers;
    }
    if (message.ipv6Resolvers?.length) {
      obj.ipv6Resolvers = message.ipv6Resolvers;
    }
    if (message.database !== "") {
      obj.database = message.database;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Configuration>, I>>(base?: I): Configuration {
    return Configuration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Configuration>, I>>(object: I): Configuration {
    const message = createBaseConfiguration();
    message.logLevel = object.logLevel ?? 0;
    message.webPort = object.webPort ?? 0;
    message.certificatePath = object.certificatePath ?? "";
    message.keyPath = object.keyPath ?? "";
    message.refreshCron = object.refreshCron ?? "";
    message.dnsServers = object.dnsServers?.map((e) => e) || [];
    message.ipv4Resolvers = object.ipv4Resolvers?.map((e) => e) || [];
    message.ipv6Resolvers = object.ipv6Resolvers?.map((e) => e) || [];
    message.database = object.database ?? "";
    return message;
  },
};

function createBaseLogEntry(): LogEntry {
  return { timestamp: 0, level: 0, message: "" };
}

export const LogEntry: MessageFns<LogEntry> = {
  encode(message: LogEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestamp !== 0) {
      writer.uint32(8).int64(message.timestamp);
    }
    if (message.level !== 0) {
      writer.uint32(16).int32(message.level);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.level = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogEntry {
    return {
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: LogEntry): unknown {
    const obj: any = {};
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogEntry>, I>>(base?: I): LogEntry {
    return LogEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogEntry>, I>>(object: I): LogEntry {
    const message = createBaseLogEntry();
    message.timestamp = object.timestamp ?? 0;
    message.level = object.level ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

/** HDNS is the main service for HDNS. */
export type HDNSDefinition = typeof HDNSDefinition;
export const HDNSDefinition = {
  name: "HDNS",
  fullName: "service.HDNS",
  methods: {
    /** GetZones returns all zones. */
    getZones: {
      name: "GetZones",
      requestType: Request as typeof Request,
      requestStream: false,
      responseType: ZoneList as typeof ZoneList,
      responseStream: false,
      options: {},
    },
    /** GetRecords returns all records. */
    getRecords: {
      name: "GetRecords",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: RecordList as typeof RecordList,
      responseStream: false,
      options: {},
    },
    /** UpsertRecord creates or updates a record. */
    upsertRecord: {
      name: "UpsertRecord",
      requestType: Record as typeof Record,
      requestStream: false,
      responseType: Record as typeof Record,
      responseStream: false,
      options: {},
    },
    /** DeleteRecord deletes a record. */
    deleteRecord: {
      name: "DeleteRecord",
      requestType: RecordDelete as typeof RecordDelete,
      requestStream: false,
      responseType: Empty as typeof Empty,
      responseStream: false,
      options: {},
    },
    /** RefreshRecord the record's address. */
    refreshRecord: {
      name: "RefreshRecord",
      requestType: Record as typeof Record,
      requestStream: false,
      responseType: Record as typeof Record,
      responseStream: false,
      options: {},
    },
    /** ResolveRecord resolves the record's domain. */
    resolveRecord: {
      name: "ResolveRecord",
      requestType: Record as typeof Record,
      requestStream: false,
      responseType: ResolutionResult as typeof ResolutionResult,
      responseStream: false,
      options: {},
    },
    /** StreamResolveRecord streams the resolution results for the record. */
    streamResolveRecord: {
      name: "StreamResolveRecord",
      requestType: Record as typeof Record,
      requestStream: false,
      responseType: Resolution as typeof Resolution,
      responseStream: true,
      options: {},
    },
    /** StreamAddress streams the current address. */
    streamAddress: {
      name: "StreamAddress",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: Address as typeof Address,
      responseStream: true,
      options: {},
    },
    /** GetAddress returns the current address. */
    getAddress: {
      name: "GetAddress",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: Address as typeof Address,
      responseStream: false,
      options: {},
    },
    /** GetAddressHistory returns the address history. */
    getAddressHistory: {
      name: "GetAddressHistory",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: AddressHistory as typeof AddressHistory,
      responseStream: false,
      options: {},
    },
    /** RefreshAddress refreshes the current address. */
    refreshAddress: {
      name: "RefreshAddress",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: Address as typeof Address,
      responseStream: false,
      options: {},
    },
    /** GetConfig returns the current configuration. */
    getConfig: {
      name: "GetConfig",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: Configuration as typeof Configuration,
      responseStream: false,
      options: {},
    },
    /** UpdateConfig updates the current configuration. */
    updateConfig: {
      name: "UpdateConfig",
      requestType: Configuration as typeof Configuration,
      requestStream: false,
      responseType: Configuration as typeof Configuration,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
