// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addresses.sql

package schema

import (
	"context"
	"database/sql"
)

const CreateAddress = `-- name: CreateAddress :execlastid
INSERT INTO
    addresses (
        ipv4,
        ipv6,
        current
    )
VALUES
    (?, ?, ?)
`

type CreateAddressParams struct {
	Ipv4    sql.NullString
	Ipv6    sql.NullString
	Current bool
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, CreateAddress, arg.Ipv4, arg.Ipv6, arg.Current)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const DeleteAddress = `-- name: DeleteAddress :exec
DELETE FROM addresses
WHERE
    id = ?
`

func (q *Queries) DeleteAddress(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteAddress, id)
	return err
}

const GetAddressByID = `-- name: GetAddressByID :one
SELECT
    id, created_at, updated_at, ipv4, ipv6, current
FROM
    addresses
WHERE
    id = ?
`

func (q *Queries) GetAddressByID(ctx context.Context, id int64) (*Address, error) {
	row := q.db.QueryRowContext(ctx, GetAddressByID, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ipv4,
		&i.Ipv6,
		&i.Current,
	)
	return &i, err
}

const GetCurrentAddress = `-- name: GetCurrentAddress :one
SELECT
    id, created_at, updated_at, ipv4, ipv6, current
FROM
    addresses
WHERE
    current = TRUE
LIMIT
    1
`

func (q *Queries) GetCurrentAddress(ctx context.Context) (*Address, error) {
	row := q.db.QueryRowContext(ctx, GetCurrentAddress)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ipv4,
		&i.Ipv6,
		&i.Current,
	)
	return &i, err
}

const ListAddresses = `-- name: ListAddresses :many
SELECT
    id, created_at, updated_at, ipv4, ipv6, current
FROM
    addresses
ORDER BY
    id DESC
`

func (q *Queries) ListAddresses(ctx context.Context) ([]*Address, error) {
	rows, err := q.db.QueryContext(ctx, ListAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Ipv4,
			&i.Ipv6,
			&i.Current,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ResetCurrentAddresses = `-- name: ResetCurrentAddresses :exec
UPDATE addresses
SET
    current = FALSE
WHERE
    current = TRUE
`

func (q *Queries) ResetCurrentAddresses(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ResetCurrentAddresses)
	return err
}

const UpdateAddress = `-- name: UpdateAddress :execlastid
UPDATE addresses
SET
    ipv4 = ?,
    ipv6 = ?,
    current = ?
WHERE
    id = ?
`

type UpdateAddressParams struct {
	Ipv4    sql.NullString
	Ipv6    sql.NullString
	Current bool
	ID      int64
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, UpdateAddress,
		arg.Ipv4,
		arg.Ipv6,
		arg.Current,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
