// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: certificates.sql

package schema

import (
	"context"
	"database/sql"
)

const CreateCertificate = `-- name: CreateCertificate :execlastid
INSERT INTO
    certificates (record_id, domains, status, cert_path, key_path)
VALUES
    (?, ?, ?, ?, ?)
`

type CreateCertificateParams struct {
	RecordID int64
	Domains  string
	Status   string
	CertPath string
	KeyPath  string
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, CreateCertificate,
		arg.RecordID,
		arg.Domains,
		arg.Status,
		arg.CertPath,
		arg.KeyPath,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const DeleteCertificate = `-- name: DeleteCertificate :exec
DELETE FROM certificates
WHERE
    id = ?
`

func (q *Queries) DeleteCertificate(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteCertificate, id)
	return err
}

const DeleteCertificateByRecord = `-- name: DeleteCertificateByRecord :exec
DELETE FROM certificates
WHERE
    record_id = ?
`

func (q *Queries) DeleteCertificateByRecord(ctx context.Context, recordID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteCertificateByRecord, recordID)
	return err
}

const GetCertificate = `-- name: GetCertificate :one
SELECT
    id, created_at, updated_at, record_id, domains, status, not_before, not_after, serial, last_error, cert_path, key_path
FROM
    certificates
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetCertificate(ctx context.Context, id int64) (*Certificate, error) {
	row := q.db.QueryRowContext(ctx, GetCertificate, id)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecordID,
		&i.Domains,
		&i.Status,
		&i.NotBefore,
		&i.NotAfter,
		&i.Serial,
		&i.LastError,
		&i.CertPath,
		&i.KeyPath,
	)
	return &i, err
}

const GetCertificateByRecord = `-- name: GetCertificateByRecord :one
SELECT
    id, created_at, updated_at, record_id, domains, status, not_before, not_after, serial, last_error, cert_path, key_path
FROM
    certificates
WHERE
    record_id = ?
LIMIT
    1
`

func (q *Queries) GetCertificateByRecord(ctx context.Context, recordID int64) (*Certificate, error) {
	row := q.db.QueryRowContext(ctx, GetCertificateByRecord, recordID)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecordID,
		&i.Domains,
		&i.Status,
		&i.NotBefore,
		&i.NotAfter,
		&i.Serial,
		&i.LastError,
		&i.CertPath,
		&i.KeyPath,
	)
	return &i, err
}

const ListCertificates = `-- name: ListCertificates :many
SELECT
    id, created_at, updated_at, record_id, domains, status, not_before, not_after, serial, last_error, cert_path, key_path
FROM
    certificates
ORDER BY
    created_at DESC
`

func (q *Queries) ListCertificates(ctx context.Context) ([]*Certificate, error) {
	rows, err := q.db.QueryContext(ctx, ListCertificates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Certificate{}
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecordID,
			&i.Domains,
			&i.Status,
			&i.NotBefore,
			&i.NotAfter,
			&i.Serial,
			&i.LastError,
			&i.CertPath,
			&i.KeyPath,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListCertificatesForRenewal = `-- name: ListCertificatesForRenewal :many
SELECT
    id, created_at, updated_at, record_id, domains, status, not_before, not_after, serial, last_error, cert_path, key_path
FROM
    certificates
WHERE
    not_after IS NOT NULL
    AND not_after <= ?
ORDER BY
    not_after ASC
`

func (q *Queries) ListCertificatesForRenewal(ctx context.Context, notAfter sql.NullTime) ([]*Certificate, error) {
	rows, err := q.db.QueryContext(ctx, ListCertificatesForRenewal, notAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Certificate{}
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecordID,
			&i.Domains,
			&i.Status,
			&i.NotBefore,
			&i.NotAfter,
			&i.Serial,
			&i.LastError,
			&i.CertPath,
			&i.KeyPath,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateCertificate = `-- name: UpdateCertificate :exec
UPDATE certificates
SET
    domains = ?,
    status = ?,
    not_before = ?,
    not_after = ?,
    serial = ?,
    last_error = ?,
    cert_path = ?,
    key_path = ?
WHERE
    id = ?
`

type UpdateCertificateParams struct {
	Domains   string
	Status    string
	NotBefore sql.NullTime
	NotAfter  sql.NullTime
	Serial    sql.NullString
	LastError sql.NullString
	CertPath  string
	KeyPath   string
	ID        int64
}

func (q *Queries) UpdateCertificate(ctx context.Context, arg UpdateCertificateParams) error {
	_, err := q.db.ExecContext(ctx, UpdateCertificate,
		arg.Domains,
		arg.Status,
		arg.NotBefore,
		arg.NotAfter,
		arg.Serial,
		arg.LastError,
		arg.CertPath,
		arg.KeyPath,
		arg.ID,
	)
	return err
}

const UpdateCertificateStatus = `-- name: UpdateCertificateStatus :exec
UPDATE certificates
SET
    status = ?,
    last_error = ?
WHERE
    id = ?
`

type UpdateCertificateStatusParams struct {
	Status    string
	LastError sql.NullString
	ID        int64
}

func (q *Queries) UpdateCertificateStatus(ctx context.Context, arg UpdateCertificateStatusParams) error {
	_, err := q.db.ExecContext(ctx, UpdateCertificateStatus, arg.Status, arg.LastError, arg.ID)
	return err
}
