// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package schema

import (
	"database/sql"
)

type Address struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Ipv4      sql.NullString
	Ipv6      sql.NullString
	Current   bool
}

type Record struct {
	ID          int64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Token       string
	ZoneID      int64
	Domain      string
	Name        string
	Ttl         int32
	AddressID   sql.NullInt64
	LastRefresh sql.NullTime
}

type Release struct {
	ID        int64
	GitTag    string
	GitCommit string
	GitShort  sql.NullString
	BuildDate sql.NullString
	GoVersion sql.NullString
	Platform  sql.NullString
}
