// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package schema

import (
	"database/sql"
	"time"
)

type Address struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Ipv4      sql.NullString
	Ipv6      sql.NullString
	Current   bool
}

type Certificate struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	RecordID  int64
	// comma-separated list of certificate SANs
	Domains string
	// pending, valid, failed, expired
	Status    string
	NotBefore sql.NullTime
	NotAfter  sql.NullTime
	Serial    sql.NullString
	LastError sql.NullString
	CertPath  string
	KeyPath   string
}

type CertificateJob struct {
	ID            int64
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	RecordID      int64
	CertificateID sql.NullInt64
	// manual, scheduled
	Source string
	// running, success, failed
	Status     string
	StartedAt  time.Time
	FinishedAt sql.NullTime
	Error      sql.NullString
}

type Record struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	// AES-256-GCM encrypted Hetzner API token (base64url-encoded nonce+ciphertext+tag)
	Token     string
	ZoneID    int64
	Domain    string
	Name      string
	Ttl       int32
	AddressID sql.NullInt64
	// 1=ddns, 2=cert, 3=both
	Purpose         int8
	IncludeWildcard bool
}

type Release struct {
	ID        int64
	GitTag    string
	GitCommit string
	GitShort  sql.NullString
	BuildDate sql.NullString
	GoVersion sql.NullString
	Platform  sql.NullString
}

type Task struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	RecordID  int64
	Name      string
	// 1=ip, 2=cert, 3=both
	TriggerOn int8
	Method    string
	Url       string
	// AES-256-GCM encrypted JSON object of HTTP headers (base64url-encoded nonce+ciphertext+tag)
	Headers sql.NullString
	Body    sql.NullString
	// inject the issued certificate and private key into the webhook body
	IncludeCertificate bool
	Enabled            bool
	LastRun            sql.NullTime
	LastStatus         sql.NullString
	LastError          sql.NullString
	// certificate payload format: pem, pkcs12
	CertificateFormat string
}

type TaskRun struct {
	ID               int64
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	TaskID           int64
	RecordID         int64
	CertificateJobID sql.NullInt64
	// 1=ip, 2=cert, 3=both
	TriggerOn int8
	// success, failed
	Status         string
	ResponseStatus sql.NullString
	Error          sql.NullString
	StartedAt      time.Time
	FinishedAt     sql.NullTime
}
