// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: records.sql

package schema

import (
	"context"
	"database/sql"
)

const CreateRecord = `-- name: CreateRecord :execlastid
INSERT INTO
    records (token, zone_id, domain, name, ttl)
VALUES
    (?, ?, ?, ?, ?)
`

type CreateRecordParams struct {
	Token  string
	ZoneID int64
	Domain string
	Name   string
	Ttl    int32
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, CreateRecord,
		arg.Token,
		arg.ZoneID,
		arg.Domain,
		arg.Name,
		arg.Ttl,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const DeleteRecord = `-- name: DeleteRecord :exec
DELETE FROM records
WHERE
    id = ?
`

func (q *Queries) DeleteRecord(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteRecord, id)
	return err
}

const GetRecord = `-- name: GetRecord :one
SELECT
    id, created_at, updated_at, token, zone_id, domain, name, ttl, address_id
FROM
    records
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetRecord(ctx context.Context, id int64) (*Record, error) {
	row := q.db.QueryRowContext(ctx, GetRecord, id)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
		&i.ZoneID,
		&i.Domain,
		&i.Name,
		&i.Ttl,
		&i.AddressID,
	)
	return &i, err
}

const ListRecords = `-- name: ListRecords :many
SELECT
    r.id, r.created_at, r.updated_at, r.token, r.zone_id, r.domain, r.name, r.ttl, r.address_id
FROM
    records as r
WHERE
    CASE
        WHEN ? IS NOT NULL THEN r.name LIKE CONCAT('%', ?, '%')
        OR r.domain LIKE CONCAT('%', ?, '%')
        ELSE TRUE
    END
ORDER BY
    r.domain ASC,
    r.name ASC
`

type ListRecordsParams struct {
	Search interface{}
}

func (q *Queries) ListRecords(ctx context.Context, arg ListRecordsParams) ([]*Record, error) {
	rows, err := q.db.QueryContext(ctx, ListRecords, arg.Search, arg.Search, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Token,
			&i.ZoneID,
			&i.Domain,
			&i.Name,
			&i.Ttl,
			&i.AddressID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateRecord = `-- name: UpdateRecord :exec
UPDATE records
SET
    token = ?,
    zone_id = ?,
    domain = ?,
    name = ?,
    ttl = ?
WHERE
    id = ?
`

type UpdateRecordParams struct {
	Token  string
	ZoneID int64
	Domain string
	Name   string
	Ttl    int32
	ID     int64
}

func (q *Queries) UpdateRecord(ctx context.Context, arg UpdateRecordParams) error {
	_, err := q.db.ExecContext(ctx, UpdateRecord,
		arg.Token,
		arg.ZoneID,
		arg.Domain,
		arg.Name,
		arg.Ttl,
		arg.ID,
	)
	return err
}

const UpdateRecordAddress = `-- name: UpdateRecordAddress :exec
UPDATE records
SET
    address_id = ?
WHERE
    id = ?
`

type UpdateRecordAddressParams struct {
	AddressID sql.NullInt64
	ID        int64
}

func (q *Queries) UpdateRecordAddress(ctx context.Context, arg UpdateRecordAddressParams) error {
	_, err := q.db.ExecContext(ctx, UpdateRecordAddress, arg.AddressID, arg.ID)
	return err
}
