// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: releases.sql

package schema

import (
	"context"
	"database/sql"
)

const CreateRelease = `-- name: CreateRelease :execlastid
INSERT INTO
    releases (
        git_tag,
        git_commit,
        git_short,
        build_date,
        go_version,
        platform
    )
VALUES
    (?, ?, ?, ?, ?, ?) ON DUPLICATE KEY
UPDATE id = id
`

type CreateReleaseParams struct {
	GitTag    string
	GitCommit string
	GitShort  sql.NullString
	BuildDate sql.NullString
	GoVersion sql.NullString
	Platform  sql.NullString
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, CreateRelease,
		arg.GitTag,
		arg.GitCommit,
		arg.GitShort,
		arg.BuildDate,
		arg.GoVersion,
		arg.Platform,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const DeleteRelease = `-- name: DeleteRelease :exec
DELETE FROM releases
WHERE
    id = ?
`

func (q *Queries) DeleteRelease(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteRelease, id)
	return err
}

const GetLatestRelease = `-- name: GetLatestRelease :one
SELECT
    id, git_tag, git_commit, git_short, build_date, go_version, platform
FROM
    releases
ORDER BY
    id DESC
LIMIT
    1
`

func (q *Queries) GetLatestRelease(ctx context.Context) (*Release, error) {
	row := q.db.QueryRowContext(ctx, GetLatestRelease)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.GitTag,
		&i.GitCommit,
		&i.GitShort,
		&i.BuildDate,
		&i.GoVersion,
		&i.Platform,
	)
	return &i, err
}

const GetRelease = `-- name: GetRelease :one
SELECT
    id, git_tag, git_commit, git_short, build_date, go_version, platform
FROM
    releases
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetRelease(ctx context.Context, id int64) (*Release, error) {
	row := q.db.QueryRowContext(ctx, GetRelease, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.GitTag,
		&i.GitCommit,
		&i.GitShort,
		&i.BuildDate,
		&i.GoVersion,
		&i.Platform,
	)
	return &i, err
}

const GetReleaseByCommit = `-- name: GetReleaseByCommit :one
SELECT
    id, git_tag, git_commit, git_short, build_date, go_version, platform
FROM
    releases
WHERE
    git_commit = ?
LIMIT
    1
`

func (q *Queries) GetReleaseByCommit(ctx context.Context, gitCommit string) (*Release, error) {
	row := q.db.QueryRowContext(ctx, GetReleaseByCommit, gitCommit)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.GitTag,
		&i.GitCommit,
		&i.GitShort,
		&i.BuildDate,
		&i.GoVersion,
		&i.Platform,
	)
	return &i, err
}

const GetReleaseByTag = `-- name: GetReleaseByTag :one
SELECT
    id, git_tag, git_commit, git_short, build_date, go_version, platform
FROM
    releases
WHERE
    git_tag = ?
LIMIT
    1
`

func (q *Queries) GetReleaseByTag(ctx context.Context, gitTag string) (*Release, error) {
	row := q.db.QueryRowContext(ctx, GetReleaseByTag, gitTag)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.GitTag,
		&i.GitCommit,
		&i.GitShort,
		&i.BuildDate,
		&i.GoVersion,
		&i.Platform,
	)
	return &i, err
}

const ListReleases = `-- name: ListReleases :many
SELECT
    id, git_tag, git_commit, git_short, build_date, go_version, platform
FROM
    releases
ORDER BY
    id DESC
`

func (q *Queries) ListReleases(ctx context.Context) ([]*Release, error) {
	rows, err := q.db.QueryContext(ctx, ListReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.GitTag,
			&i.GitCommit,
			&i.GitShort,
			&i.BuildDate,
			&i.GoVersion,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateRelease = `-- name: UpdateRelease :exec
UPDATE releases
SET
    git_tag = ?,
    git_commit = ?,
    git_short = ?,
    build_date = ?,
    go_version = ?,
    platform = ?
WHERE
    id = ?
`

type UpdateReleaseParams struct {
	GitTag    string
	GitCommit string
	GitShort  sql.NullString
	BuildDate sql.NullString
	GoVersion sql.NullString
	Platform  sql.NullString
	ID        int64
}

func (q *Queries) UpdateRelease(ctx context.Context, arg UpdateReleaseParams) error {
	_, err := q.db.ExecContext(ctx, UpdateRelease,
		arg.GitTag,
		arg.GitCommit,
		arg.GitShort,
		arg.BuildDate,
		arg.GoVersion,
		arg.Platform,
		arg.ID,
	)
	return err
}
