// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package schema

import (
	"context"
	"database/sql"
)

const CreateTask = `-- name: CreateTask :execlastid
INSERT INTO
    tasks (record_id, name, trigger_on, method, url, headers, body, enabled, include_certificate, certificate_format)
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	RecordID           int64
	Name               string
	TriggerOn          int8
	Method             string
	Url                string
	Headers            sql.NullString
	Body               sql.NullString
	Enabled            bool
	IncludeCertificate bool
	CertificateFormat  string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, CreateTask,
		arg.RecordID,
		arg.Name,
		arg.TriggerOn,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Body,
		arg.Enabled,
		arg.IncludeCertificate,
		arg.CertificateFormat,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const DeleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE
    id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteTask, id)
	return err
}

const GetTask = `-- name: GetTask :one
SELECT
    id, created_at, updated_at, record_id, name, trigger_on, method, url, headers, body, include_certificate, enabled, last_run, last_status, last_error, certificate_format
FROM
    tasks
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (*Task, error) {
	row := q.db.QueryRowContext(ctx, GetTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecordID,
		&i.Name,
		&i.TriggerOn,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.Body,
		&i.IncludeCertificate,
		&i.Enabled,
		&i.LastRun,
		&i.LastStatus,
		&i.LastError,
		&i.CertificateFormat,
	)
	return &i, err
}

const ListEnabledTasksByRecord = `-- name: ListEnabledTasksByRecord :many
SELECT
    id, created_at, updated_at, record_id, name, trigger_on, method, url, headers, body, include_certificate, enabled, last_run, last_status, last_error, certificate_format
FROM
    tasks
WHERE
    record_id = ?
    AND enabled = TRUE
ORDER BY
    created_at ASC
`

func (q *Queries) ListEnabledTasksByRecord(ctx context.Context, recordID int64) ([]*Task, error) {
	rows, err := q.db.QueryContext(ctx, ListEnabledTasksByRecord, recordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecordID,
			&i.Name,
			&i.TriggerOn,
			&i.Method,
			&i.Url,
			&i.Headers,
			&i.Body,
			&i.IncludeCertificate,
			&i.Enabled,
			&i.LastRun,
			&i.LastStatus,
			&i.LastError,
			&i.CertificateFormat,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTasks = `-- name: ListTasks :many
SELECT
    id, created_at, updated_at, record_id, name, trigger_on, method, url, headers, body, include_certificate, enabled, last_run, last_status, last_error, certificate_format
FROM
    tasks
ORDER BY
    created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]*Task, error) {
	rows, err := q.db.QueryContext(ctx, ListTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecordID,
			&i.Name,
			&i.TriggerOn,
			&i.Method,
			&i.Url,
			&i.Headers,
			&i.Body,
			&i.IncludeCertificate,
			&i.Enabled,
			&i.LastRun,
			&i.LastStatus,
			&i.LastError,
			&i.CertificateFormat,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTasksByRecord = `-- name: ListTasksByRecord :many
SELECT
    id, created_at, updated_at, record_id, name, trigger_on, method, url, headers, body, include_certificate, enabled, last_run, last_status, last_error, certificate_format
FROM
    tasks
WHERE
    record_id = ?
ORDER BY
    created_at DESC
`

func (q *Queries) ListTasksByRecord(ctx context.Context, recordID int64) ([]*Task, error) {
	rows, err := q.db.QueryContext(ctx, ListTasksByRecord, recordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecordID,
			&i.Name,
			&i.TriggerOn,
			&i.Method,
			&i.Url,
			&i.Headers,
			&i.Body,
			&i.IncludeCertificate,
			&i.Enabled,
			&i.LastRun,
			&i.LastStatus,
			&i.LastError,
			&i.CertificateFormat,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET
    record_id = ?,
    name = ?,
    trigger_on = ?,
    method = ?,
    url = ?,
    headers = ?,
    body = ?,
    enabled = ?,
    include_certificate = ?,
    certificate_format = ?
WHERE
    id = ?
`

type UpdateTaskParams struct {
	RecordID           int64
	Name               string
	TriggerOn          int8
	Method             string
	Url                string
	Headers            sql.NullString
	Body               sql.NullString
	Enabled            bool
	IncludeCertificate bool
	CertificateFormat  string
	ID                 int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, UpdateTask,
		arg.RecordID,
		arg.Name,
		arg.TriggerOn,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Body,
		arg.Enabled,
		arg.IncludeCertificate,
		arg.CertificateFormat,
		arg.ID,
	)
	return err
}

const UpdateTaskResult = `-- name: UpdateTaskResult :exec
UPDATE tasks
SET
    last_run = ?,
    last_status = ?,
    last_error = ?
WHERE
    id = ?
`

type UpdateTaskResultParams struct {
	LastRun    sql.NullTime
	LastStatus sql.NullString
	LastError  sql.NullString
	ID         int64
}

func (q *Queries) UpdateTaskResult(ctx context.Context, arg UpdateTaskResultParams) error {
	_, err := q.db.ExecContext(ctx, UpdateTaskResult,
		arg.LastRun,
		arg.LastStatus,
		arg.LastError,
		arg.ID,
	)
	return err
}
