// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: api.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Address represents an IP address.
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Ipv4          string                 `protobuf:"bytes,4,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          string                 `protobuf:"bytes,5,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	Current       bool                   `protobuf:"varint,6,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Address) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Address) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Address) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *Address) GetIpv6() string {
	if x != nil {
		return x.Ipv6
	}
	return ""
}

func (x *Address) GetCurrent() bool {
	if x != nil {
		return x.Current
	}
	return false
}

type AddressHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressHistory) Reset() {
	*x = AddressHistory{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressHistory) ProtoMessage() {}

func (x *AddressHistory) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressHistory.ProtoReflect.Descriptor instead.
func (*AddressHistory) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *AddressHistory) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// Record represents a DNS record.
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	ZoneId        string                 `protobuf:"bytes,5,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Domain        string                 `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Ttl           uint32                 `protobuf:"varint,8,opt,name=ttl,proto3" json:"ttl,omitempty"`
	AddressId     int64                  `protobuf:"varint,9,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	Address       *Address               `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	LastRefresh   int64                  `protobuf:"varint,11,opt,name=last_refresh,json=lastRefresh,proto3" json:"last_refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *Record) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Record) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Record) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Record) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Record) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *Record) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Record) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Record) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Record) GetAddressId() int64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *Record) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Record) GetLastRefresh() int64 {
	if x != nil {
		return x.LastRefresh
	}
	return 0
}

type RecordList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordList) Reset() {
	*x = RecordList{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordList) ProtoMessage() {}

func (x *RecordList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordList.ProtoReflect.Descriptor instead.
func (*RecordList) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *RecordList) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type RecordDelete struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Record            *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	DeleteFromHetzner bool                   `protobuf:"varint,2,opt,name=delete_from_hetzner,json=deleteFromHetzner,proto3" json:"delete_from_hetzner,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecordDelete) Reset() {
	*x = RecordDelete{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordDelete) ProtoMessage() {}

func (x *RecordDelete) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordDelete.ProtoReflect.Descriptor instead.
func (*RecordDelete) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *RecordDelete) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *RecordDelete) GetDeleteFromHetzner() bool {
	if x != nil {
		return x.DeleteFromHetzner
	}
	return false
}

type Zone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RecordCount   int64                  `protobuf:"varint,3,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *Zone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Zone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Zone) GetRecordCount() int64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

type ZoneList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zones         []*Zone                `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneList) Reset() {
	*x = ZoneList{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneList) ProtoMessage() {}

func (x *ZoneList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneList.ProtoReflect.Descriptor instead.
func (*ZoneList) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *ZoneList) GetZones() []*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

type Resolution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	ResponseTime  int64                  `protobuf:"varint,3,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resolution) Reset() {
	*x = Resolution{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resolution) ProtoMessage() {}

func (x *Resolution) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resolution.ProtoReflect.Descriptor instead.
func (*Resolution) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *Resolution) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Resolution) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Resolution) GetResponseTime() int64 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

func (x *Resolution) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ResolutionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resolutions   []*Resolution          `protobuf:"bytes,2,rep,name=resolutions,proto3" json:"resolutions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolutionResult) Reset() {
	*x = ResolutionResult{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolutionResult) ProtoMessage() {}

func (x *ResolutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolutionResult.ProtoReflect.Descriptor instead.
func (*ResolutionResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *ResolutionResult) GetResolutions() []*Resolution {
	if x != nil {
		return x.Resolutions
	}
	return nil
}

type Configuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Database      *Database              `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *Configuration) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Configuration) GetDatabase() *Database {
	if x != nil {
		return x.Database
	}
	return nil
}

type Service struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LogLevel        int32                  `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	WebPort         int32                  `protobuf:"varint,2,opt,name=web_port,json=webPort,proto3" json:"web_port,omitempty"`
	CertificatePath string                 `protobuf:"bytes,3,opt,name=certificate_path,json=certificatePath,proto3" json:"certificate_path,omitempty"`
	KeyPath         string                 `protobuf:"bytes,4,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	RefreshCron     string                 `protobuf:"bytes,5,opt,name=refresh_cron,json=refreshCron,proto3" json:"refresh_cron,omitempty"`
	DnsServers      []string               `protobuf:"bytes,6,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`
	Ipv4Resolvers   []string               `protobuf:"bytes,7,rep,name=ipv4_resolvers,json=ipv4Resolvers,proto3" json:"ipv4_resolvers,omitempty"`
	Ipv6Resolvers   []string               `protobuf:"bytes,8,rep,name=ipv6_resolvers,json=ipv6Resolvers,proto3" json:"ipv6_resolvers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *Service) GetLogLevel() int32 {
	if x != nil {
		return x.LogLevel
	}
	return 0
}

func (x *Service) GetWebPort() int32 {
	if x != nil {
		return x.WebPort
	}
	return 0
}

func (x *Service) GetCertificatePath() string {
	if x != nil {
		return x.CertificatePath
	}
	return ""
}

func (x *Service) GetKeyPath() string {
	if x != nil {
		return x.KeyPath
	}
	return ""
}

func (x *Service) GetRefreshCron() string {
	if x != nil {
		return x.RefreshCron
	}
	return ""
}

func (x *Service) GetDnsServers() []string {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

func (x *Service) GetIpv4Resolvers() []string {
	if x != nil {
		return x.Ipv4Resolvers
	}
	return nil
}

func (x *Service) GetIpv6Resolvers() []string {
	if x != nil {
		return x.Ipv6Resolvers
	}
	return nil
}

type Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *Database) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Database) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Database) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Database) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Database) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\aservice\"\a\n" +
	"\x05Empty\"\x1f\n" +
	"\aRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x99\x01\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12\x12\n" +
	"\x04ipv4\x18\x04 \x01(\tR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\x05 \x01(\tR\x04ipv6\x12\x18\n" +
	"\acurrent\x18\x06 \x01(\bR\acurrent\"@\n" +
	"\x0eAddressHistory\x12.\n" +
	"\taddresses\x18\x01 \x03(\v2\x10.service.AddressR\taddresses\"\xb1\x02\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x17\n" +
	"\azone_id\x18\x05 \x01(\tR\x06zoneId\x12\x16\n" +
	"\x06domain\x18\x06 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x10\n" +
	"\x03ttl\x18\b \x01(\rR\x03ttl\x12\x1d\n" +
	"\n" +
	"address_id\x18\t \x01(\x03R\taddressId\x12*\n" +
	"\aaddress\x18\n" +
	" \x01(\v2\x10.service.AddressR\aaddress\x12!\n" +
	"\flast_refresh\x18\v \x01(\x03R\vlastRefresh\"7\n" +
	"\n" +
	"RecordList\x12)\n" +
	"\arecords\x18\x01 \x03(\v2\x0f.service.RecordR\arecords\"g\n" +
	"\fRecordDelete\x12'\n" +
	"\x06record\x18\x01 \x01(\v2\x0f.service.RecordR\x06record\x12.\n" +
	"\x13delete_from_hetzner\x18\x02 \x01(\bR\x11deleteFromHetzner\"M\n" +
	"\x04Zone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\frecord_count\x18\x03 \x01(\x03R\vrecordCount\"/\n" +
	"\bZoneList\x12#\n" +
	"\x05zones\x18\x01 \x03(\v2\r.service.ZoneR\x05zones\"}\n" +
	"\n" +
	"Resolution\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12#\n" +
	"\rresponse_time\x18\x03 \x01(\x03R\fresponseTime\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"I\n" +
	"\x10ResolutionResult\x125\n" +
	"\vresolutions\x18\x02 \x03(\v2\x13.service.ResolutionR\vresolutions\"j\n" +
	"\rConfiguration\x12*\n" +
	"\aservice\x18\x01 \x01(\v2\x10.service.ServiceR\aservice\x12-\n" +
	"\bdatabase\x18\x02 \x01(\v2\x11.service.DatabaseR\bdatabase\"\x99\x02\n" +
	"\aService\x12\x1b\n" +
	"\tlog_level\x18\x01 \x01(\x05R\blogLevel\x12\x19\n" +
	"\bweb_port\x18\x02 \x01(\x05R\awebPort\x12)\n" +
	"\x10certificate_path\x18\x03 \x01(\tR\x0fcertificatePath\x12\x19\n" +
	"\bkey_path\x18\x04 \x01(\tR\akeyPath\x12!\n" +
	"\frefresh_cron\x18\x05 \x01(\tR\vrefreshCron\x12\x1f\n" +
	"\vdns_servers\x18\x06 \x03(\tR\n" +
	"dnsServers\x12%\n" +
	"\x0eipv4_resolvers\x18\a \x03(\tR\ripv4Resolvers\x12%\n" +
	"\x0eipv6_resolvers\x18\b \x03(\tR\ripv6Resolvers\"~\n" +
	"\bDatabase\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"X\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xff\x05\n" +
	"\x04HDNS\x12/\n" +
	"\bGetZones\x12\x10.service.Request\x1a\x11.service.ZoneList\x121\n" +
	"\n" +
	"GetRecords\x12\x0e.service.Empty\x1a\x13.service.RecordList\x120\n" +
	"\fUpsertRecord\x12\x0f.service.Record\x1a\x0f.service.Record\x125\n" +
	"\fDeleteRecord\x12\x15.service.RecordDelete\x1a\x0e.service.Empty\x121\n" +
	"\rRefreshRecord\x12\x0f.service.Record\x1a\x0f.service.Record\x12:\n" +
	"\rResolveRecord\x12\x0e.service.Empty\x1a\x19.service.ResolutionResult\x12<\n" +
	"\x13StreamResolveRecord\x12\x0e.service.Empty\x1a\x13.service.Resolution0\x01\x123\n" +
	"\rStreamAddress\x12\x0e.service.Empty\x1a\x10.service.Address0\x01\x12.\n" +
	"\n" +
	"GetAddress\x12\x0e.service.Empty\x1a\x10.service.Address\x12<\n" +
	"\x11GetAddressHistory\x12\x0e.service.Empty\x1a\x17.service.AddressHistory\x122\n" +
	"\x0eRefreshAddress\x12\x0e.service.Empty\x1a\x10.service.Address\x123\n" +
	"\tGetConfig\x12\x0e.service.Empty\x1a\x16.service.Configuration\x12>\n" +
	"\fUpdateConfig\x12\x16.service.Configuration\x1a\x16.service.Configuration\x121\n" +
	"\n" +
	"StreamLogs\x12\x0e.service.Empty\x1a\x11.service.LogEntry0\x01B5H\x01Z1github.com/valentin-kaiser/hdns/pkg/proto/serviceb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_goTypes = []any{
	(*Empty)(nil),            // 0: service.Empty
	(*Request)(nil),          // 1: service.Request
	(*Address)(nil),          // 2: service.Address
	(*AddressHistory)(nil),   // 3: service.AddressHistory
	(*Record)(nil),           // 4: service.Record
	(*RecordList)(nil),       // 5: service.RecordList
	(*RecordDelete)(nil),     // 6: service.RecordDelete
	(*Zone)(nil),             // 7: service.Zone
	(*ZoneList)(nil),         // 8: service.ZoneList
	(*Resolution)(nil),       // 9: service.Resolution
	(*ResolutionResult)(nil), // 10: service.ResolutionResult
	(*Configuration)(nil),    // 11: service.Configuration
	(*Service)(nil),          // 12: service.Service
	(*Database)(nil),         // 13: service.Database
	(*LogEntry)(nil),         // 14: service.LogEntry
}
var file_api_proto_depIdxs = []int32{
	2,  // 0: service.AddressHistory.addresses:type_name -> service.Address
	2,  // 1: service.Record.address:type_name -> service.Address
	4,  // 2: service.RecordList.records:type_name -> service.Record
	4,  // 3: service.RecordDelete.record:type_name -> service.Record
	7,  // 4: service.ZoneList.zones:type_name -> service.Zone
	9,  // 5: service.ResolutionResult.resolutions:type_name -> service.Resolution
	12, // 6: service.Configuration.service:type_name -> service.Service
	13, // 7: service.Configuration.database:type_name -> service.Database
	1,  // 8: service.HDNS.GetZones:input_type -> service.Request
	0,  // 9: service.HDNS.GetRecords:input_type -> service.Empty
	4,  // 10: service.HDNS.UpsertRecord:input_type -> service.Record
	6,  // 11: service.HDNS.DeleteRecord:input_type -> service.RecordDelete
	4,  // 12: service.HDNS.RefreshRecord:input_type -> service.Record
	0,  // 13: service.HDNS.ResolveRecord:input_type -> service.Empty
	0,  // 14: service.HDNS.StreamResolveRecord:input_type -> service.Empty
	0,  // 15: service.HDNS.StreamAddress:input_type -> service.Empty
	0,  // 16: service.HDNS.GetAddress:input_type -> service.Empty
	0,  // 17: service.HDNS.GetAddressHistory:input_type -> service.Empty
	0,  // 18: service.HDNS.RefreshAddress:input_type -> service.Empty
	0,  // 19: service.HDNS.GetConfig:input_type -> service.Empty
	11, // 20: service.HDNS.UpdateConfig:input_type -> service.Configuration
	0,  // 21: service.HDNS.StreamLogs:input_type -> service.Empty
	8,  // 22: service.HDNS.GetZones:output_type -> service.ZoneList
	5,  // 23: service.HDNS.GetRecords:output_type -> service.RecordList
	4,  // 24: service.HDNS.UpsertRecord:output_type -> service.Record
	0,  // 25: service.HDNS.DeleteRecord:output_type -> service.Empty
	4,  // 26: service.HDNS.RefreshRecord:output_type -> service.Record
	10, // 27: service.HDNS.ResolveRecord:output_type -> service.ResolutionResult
	9,  // 28: service.HDNS.StreamResolveRecord:output_type -> service.Resolution
	2,  // 29: service.HDNS.StreamAddress:output_type -> service.Address
	2,  // 30: service.HDNS.GetAddress:output_type -> service.Address
	3,  // 31: service.HDNS.GetAddressHistory:output_type -> service.AddressHistory
	2,  // 32: service.HDNS.RefreshAddress:output_type -> service.Address
	11, // 33: service.HDNS.GetConfig:output_type -> service.Configuration
	11, // 34: service.HDNS.UpdateConfig:output_type -> service.Configuration
	14, // 35: service.HDNS.StreamLogs:output_type -> service.LogEntry
	22, // [22:36] is the sub-list for method output_type
	8,  // [8:22] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
