// Code generated by protoc-gen-go-jrpc. DO NOT EDIT.
// source: api.proto

package service

import (
	"context"
	"errors"
	"github.com/valentin-kaiser/go-core/web/jrpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// HDNSServer is the server API for HDNS service.
type HDNSServer interface {
	Descriptor() protoreflect.FileDescriptor
	GetZones(ctx context.Context, in *Request) (*ZoneList, error)
	GetRecords(ctx context.Context, in *Empty) (*RecordList, error)
	UpsertRecord(ctx context.Context, in *Record) (*Record, error)
	DeleteRecord(ctx context.Context, in *RecordDelete) (*Empty, error)
	RefreshRecord(ctx context.Context, in *Record) (*Record, error)
	ResolveRecord(ctx context.Context, in *Empty) (*ResolutionResult, error)
	StreamResolveRecord(ctx context.Context, in *Empty, out chan *Resolution) error
	StreamAddress(ctx context.Context, in *Empty, out chan *Address) error
	GetAddress(ctx context.Context, in *Empty) (*Address, error)
	GetAddressHistory(ctx context.Context, in *Empty) (*AddressHistory, error)
	RefreshAddress(ctx context.Context, in *Empty) (*Address, error)
	GetConfig(ctx context.Context, in *Empty) (*Configuration, error)
	UpdateConfig(ctx context.Context, in *Configuration) (*Configuration, error)
	StreamLogs(ctx context.Context, in *Empty, out chan *LogEntry) error
}

type UnimplementedHDNSServer struct{}

func (UnimplementedHDNSServer) Descriptor() protoreflect.FileDescriptor {
	return File_api_proto
}

func (UnimplementedHDNSServer) GetZones(ctx context.Context, in *Request) (*ZoneList, error) {
	return nil, errors.New("method HDNS.GetZones not implemented")
}

func (UnimplementedHDNSServer) GetRecords(ctx context.Context, in *Empty) (*RecordList, error) {
	return nil, errors.New("method HDNS.GetRecords not implemented")
}

func (UnimplementedHDNSServer) UpsertRecord(ctx context.Context, in *Record) (*Record, error) {
	return nil, errors.New("method HDNS.UpsertRecord not implemented")
}

func (UnimplementedHDNSServer) DeleteRecord(ctx context.Context, in *RecordDelete) (*Empty, error) {
	return nil, errors.New("method HDNS.DeleteRecord not implemented")
}

func (UnimplementedHDNSServer) RefreshRecord(ctx context.Context, in *Record) (*Record, error) {
	return nil, errors.New("method HDNS.RefreshRecord not implemented")
}

func (UnimplementedHDNSServer) ResolveRecord(ctx context.Context, in *Empty) (*ResolutionResult, error) {
	return nil, errors.New("method HDNS.ResolveRecord not implemented")
}

func (UnimplementedHDNSServer) StreamResolveRecord(ctx context.Context, in *Empty, out chan *Resolution) error {
	return errors.New("method HDNS.StreamResolveRecord not implemented")
}

func (UnimplementedHDNSServer) StreamAddress(ctx context.Context, in *Empty, out chan *Address) error {
	return errors.New("method HDNS.StreamAddress not implemented")
}

func (UnimplementedHDNSServer) GetAddress(ctx context.Context, in *Empty) (*Address, error) {
	return nil, errors.New("method HDNS.GetAddress not implemented")
}

func (UnimplementedHDNSServer) GetAddressHistory(ctx context.Context, in *Empty) (*AddressHistory, error) {
	return nil, errors.New("method HDNS.GetAddressHistory not implemented")
}

func (UnimplementedHDNSServer) RefreshAddress(ctx context.Context, in *Empty) (*Address, error) {
	return nil, errors.New("method HDNS.RefreshAddress not implemented")
}

func (UnimplementedHDNSServer) GetConfig(ctx context.Context, in *Empty) (*Configuration, error) {
	return nil, errors.New("method HDNS.GetConfig not implemented")
}

func (UnimplementedHDNSServer) UpdateConfig(ctx context.Context, in *Configuration) (*Configuration, error) {
	return nil, errors.New("method HDNS.UpdateConfig not implemented")
}

func (UnimplementedHDNSServer) StreamLogs(ctx context.Context, in *Empty, out chan *LogEntry) error {
	return errors.New("method HDNS.StreamLogs not implemented")
}

// RegisterHDNSServer registers a HDNSServer with the JSON-RPC service registry.
// It returns a *jrpc.Service that can be used to handle JSON-RPC requests.
func RegisterHDNSServer(server HDNSServer) *jrpc.Service {
	return jrpc.Register(server)
}

// Ensure UnimplementedHDNSServer implements HDNSServer
var _ HDNSServer = (*UnimplementedHDNSServer)(nil)
