// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordPurpose int32

const (
	RecordPurpose_RECORD_PURPOSE_UNSPECIFIED RecordPurpose = 0
	RecordPurpose_RECORD_PURPOSE_DDNS        RecordPurpose = 1
	RecordPurpose_RECORD_PURPOSE_CERT        RecordPurpose = 2
	RecordPurpose_RECORD_PURPOSE_BOTH        RecordPurpose = 3
)

// Enum value maps for RecordPurpose.
var (
	RecordPurpose_name = map[int32]string{
		0: "RECORD_PURPOSE_UNSPECIFIED",
		1: "RECORD_PURPOSE_DDNS",
		2: "RECORD_PURPOSE_CERT",
		3: "RECORD_PURPOSE_BOTH",
	}
	RecordPurpose_value = map[string]int32{
		"RECORD_PURPOSE_UNSPECIFIED": 0,
		"RECORD_PURPOSE_DDNS":        1,
		"RECORD_PURPOSE_CERT":        2,
		"RECORD_PURPOSE_BOTH":        3,
	}
)

func (x RecordPurpose) Enum() *RecordPurpose {
	p := new(RecordPurpose)
	*p = x
	return p
}

func (x RecordPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (RecordPurpose) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x RecordPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordPurpose.Descriptor instead.
func (RecordPurpose) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type TaskTrigger int32

const (
	TaskTrigger_TASK_TRIGGER_UNSPECIFIED TaskTrigger = 0
	TaskTrigger_TASK_TRIGGER_IP          TaskTrigger = 1
	TaskTrigger_TASK_TRIGGER_CERT        TaskTrigger = 2
	TaskTrigger_TASK_TRIGGER_BOTH        TaskTrigger = 3
)

// Enum value maps for TaskTrigger.
var (
	TaskTrigger_name = map[int32]string{
		0: "TASK_TRIGGER_UNSPECIFIED",
		1: "TASK_TRIGGER_IP",
		2: "TASK_TRIGGER_CERT",
		3: "TASK_TRIGGER_BOTH",
	}
	TaskTrigger_value = map[string]int32{
		"TASK_TRIGGER_UNSPECIFIED": 0,
		"TASK_TRIGGER_IP":          1,
		"TASK_TRIGGER_CERT":        2,
		"TASK_TRIGGER_BOTH":        3,
	}
)

func (x TaskTrigger) Enum() *TaskTrigger {
	p := new(TaskTrigger)
	*p = x
	return p
}

func (x TaskTrigger) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskTrigger) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[1].Descriptor()
}

func (TaskTrigger) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[1]
}

func (x TaskTrigger) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskTrigger.Descriptor instead.
func (TaskTrigger) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

// Address represents an IP address.
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Ipv4          string                 `protobuf:"bytes,4,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          string                 `protobuf:"bytes,5,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	Current       bool                   `protobuf:"varint,6,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Address) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Address) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Address) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *Address) GetIpv6() string {
	if x != nil {
		return x.Ipv6
	}
	return ""
}

func (x *Address) GetCurrent() bool {
	if x != nil {
		return x.Current
	}
	return false
}

type AddressHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressHistory) Reset() {
	*x = AddressHistory{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressHistory) ProtoMessage() {}

func (x *AddressHistory) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressHistory.ProtoReflect.Descriptor instead.
func (*AddressHistory) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *AddressHistory) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// Record represents a DNS record.
type Record struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Token           string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	ZoneId          int64                  `protobuf:"varint,5,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Domain          string                 `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty"`
	Name            string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Ttl             uint32                 `protobuf:"varint,8,opt,name=ttl,proto3" json:"ttl,omitempty"`
	AddressId       int64                  `protobuf:"varint,9,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	Address         *Address               `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	Purpose         RecordPurpose          `protobuf:"varint,11,opt,name=purpose,proto3,enum=service.RecordPurpose" json:"purpose,omitempty"`
	IncludeWildcard bool                   `protobuf:"varint,12,opt,name=include_wildcard,json=includeWildcard,proto3" json:"include_wildcard,omitempty"`
	Certificate     *Certificate           `protobuf:"bytes,13,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *Record) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Record) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Record) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Record) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Record) GetZoneId() int64 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *Record) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Record) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Record) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Record) GetAddressId() int64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *Record) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Record) GetPurpose() RecordPurpose {
	if x != nil {
		return x.Purpose
	}
	return RecordPurpose_RECORD_PURPOSE_UNSPECIFIED
}

func (x *Record) GetIncludeWildcard() bool {
	if x != nil {
		return x.IncludeWildcard
	}
	return false
}

func (x *Record) GetCertificate() *Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type RecordList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordList) Reset() {
	*x = RecordList{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordList) ProtoMessage() {}

func (x *RecordList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordList.ProtoReflect.Descriptor instead.
func (*RecordList) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *RecordList) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type RecordDelete struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Record            *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	DeleteFromHetzner bool                   `protobuf:"varint,2,opt,name=delete_from_hetzner,json=deleteFromHetzner,proto3" json:"delete_from_hetzner,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecordDelete) Reset() {
	*x = RecordDelete{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordDelete) ProtoMessage() {}

func (x *RecordDelete) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordDelete.ProtoReflect.Descriptor instead.
func (*RecordDelete) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *RecordDelete) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *RecordDelete) GetDeleteFromHetzner() bool {
	if x != nil {
		return x.DeleteFromHetzner
	}
	return false
}

// Certificate represents an issued Let's Encrypt certificate.
type Certificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RecordId      int64                  `protobuf:"varint,4,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Domains       string                 `protobuf:"bytes,5,opt,name=domains,proto3" json:"domains,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	NotBefore     int64                  `protobuf:"varint,7,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter      int64                  `protobuf:"varint,8,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	Serial        string                 `protobuf:"bytes,9,opt,name=serial,proto3" json:"serial,omitempty"`
	LastError     string                 `protobuf:"bytes,10,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *Certificate) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Certificate) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Certificate) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Certificate) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *Certificate) GetDomains() string {
	if x != nil {
		return x.Domains
	}
	return ""
}

func (x *Certificate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Certificate) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *Certificate) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

func (x *Certificate) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Certificate) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type CertificateList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificates  []*Certificate         `protobuf:"bytes,1,rep,name=certificates,proto3" json:"certificates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateList) Reset() {
	*x = CertificateList{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateList) ProtoMessage() {}

func (x *CertificateList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateList.ProtoReflect.Descriptor instead.
func (*CertificateList) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *CertificateList) GetCertificates() []*Certificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

// CertificateArtifact describes a downloadable certificate file.
type CertificateArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Available     bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,4,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateArtifact) Reset() {
	*x = CertificateArtifact{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateArtifact) ProtoMessage() {}

func (x *CertificateArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateArtifact.ProtoReflect.Descriptor instead.
func (*CertificateArtifact) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *CertificateArtifact) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CertificateArtifact) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CertificateArtifact) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CertificateArtifact) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

// CertificateIssuanceJob represents a single certificate issuance attempt.
type CertificateIssuanceJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    int64                  `protobuf:"varint,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	CertificateId int64                  `protobuf:"varint,8,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateIssuanceJob) Reset() {
	*x = CertificateIssuanceJob{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateIssuanceJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateIssuanceJob) ProtoMessage() {}

func (x *CertificateIssuanceJob) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateIssuanceJob.ProtoReflect.Descriptor instead.
func (*CertificateIssuanceJob) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *CertificateIssuanceJob) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CertificateIssuanceJob) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CertificateIssuanceJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CertificateIssuanceJob) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *CertificateIssuanceJob) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *CertificateIssuanceJob) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CertificateIssuanceJob) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CertificateIssuanceJob) GetCertificateId() int64 {
	if x != nil {
		return x.CertificateId
	}
	return 0
}

// CertificateTaskRun represents a webhook task execution triggered by a certificate event.
type CertificateTaskRun struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId           int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskName         string                 `protobuf:"bytes,3,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ResponseStatus   string                 `protobuf:"bytes,5,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	Error            string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt        int64                  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt       int64                  `protobuf:"varint,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	DurationMs       int64                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	CertificateJobId int64                  `protobuf:"varint,10,opt,name=certificate_job_id,json=certificateJobId,proto3" json:"certificate_job_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CertificateTaskRun) Reset() {
	*x = CertificateTaskRun{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateTaskRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateTaskRun) ProtoMessage() {}

func (x *CertificateTaskRun) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateTaskRun.ProtoReflect.Descriptor instead.
func (*CertificateTaskRun) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *CertificateTaskRun) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CertificateTaskRun) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CertificateTaskRun) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *CertificateTaskRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CertificateTaskRun) GetResponseStatus() string {
	if x != nil {
		return x.ResponseStatus
	}
	return ""
}

func (x *CertificateTaskRun) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CertificateTaskRun) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *CertificateTaskRun) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *CertificateTaskRun) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CertificateTaskRun) GetCertificateJobId() int64 {
	if x != nil {
		return x.CertificateJobId
	}
	return 0
}

// CertificateDetails aggregates certificate info, artifacts, and job history for a record.
type CertificateDetails struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	RecordId      int64                     `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	RecordName    string                    `protobuf:"bytes,2,opt,name=record_name,json=recordName,proto3" json:"record_name,omitempty"`
	RecordDomain  string                    `protobuf:"bytes,3,opt,name=record_domain,json=recordDomain,proto3" json:"record_domain,omitempty"`
	Certificate   *Certificate              `protobuf:"bytes,4,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Artifacts     []*CertificateArtifact    `protobuf:"bytes,5,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	IssuanceJobs  []*CertificateIssuanceJob `protobuf:"bytes,6,rep,name=issuance_jobs,json=issuanceJobs,proto3" json:"issuance_jobs,omitempty"`
	TaskRuns      []*CertificateTaskRun     `protobuf:"bytes,7,rep,name=task_runs,json=taskRuns,proto3" json:"task_runs,omitempty"`
	FetchedAt     int64                     `protobuf:"varint,8,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateDetails) Reset() {
	*x = CertificateDetails{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateDetails) ProtoMessage() {}

func (x *CertificateDetails) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateDetails.ProtoReflect.Descriptor instead.
func (*CertificateDetails) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *CertificateDetails) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *CertificateDetails) GetRecordName() string {
	if x != nil {
		return x.RecordName
	}
	return ""
}

func (x *CertificateDetails) GetRecordDomain() string {
	if x != nil {
		return x.RecordDomain
	}
	return ""
}

func (x *CertificateDetails) GetCertificate() *Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *CertificateDetails) GetArtifacts() []*CertificateArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *CertificateDetails) GetIssuanceJobs() []*CertificateIssuanceJob {
	if x != nil {
		return x.IssuanceJobs
	}
	return nil
}

func (x *CertificateDetails) GetTaskRuns() []*CertificateTaskRun {
	if x != nil {
		return x.TaskRuns
	}
	return nil
}

func (x *CertificateDetails) GetFetchedAt() int64 {
	if x != nil {
		return x.FetchedAt
	}
	return 0
}

// Task represents a webhook executed on IP or certificate renewal.
type Task struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RecordId  int64                  `protobuf:"varint,4,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Name      string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	TriggerOn TaskTrigger            `protobuf:"varint,6,opt,name=trigger_on,json=triggerOn,proto3,enum=service.TaskTrigger" json:"trigger_on,omitempty"`
	Method    string                 `protobuf:"bytes,7,opt,name=method,proto3" json:"method,omitempty"`
	Url       string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	// headers is a JSON object of HTTP headers. It is write-only and never
	// returned populated to avoid exposing secrets.
	Headers    string `protobuf:"bytes,9,opt,name=headers,proto3" json:"headers,omitempty"`
	Body       string `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
	Enabled    bool   `protobuf:"varint,11,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LastRun    int64  `protobuf:"varint,12,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	LastStatus string `protobuf:"bytes,13,opt,name=last_status,json=lastStatus,proto3" json:"last_status,omitempty"`
	LastError  string `protobuf:"bytes,14,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// include_certificate injects the issued certificate and private key into the
	// webhook body via the {{certificate}} and {{private_key}} placeholders.
	IncludeCertificate bool `protobuf:"varint,15,opt,name=include_certificate,json=includeCertificate,proto3" json:"include_certificate,omitempty"`
	// certificate_format controls the certificate payload representation.
	// Valid values are "pem" and "pkcs12". Defaults to "pem".
	CertificateFormat string `protobuf:"bytes,16,opt,name=certificate_format,json=certificateFormat,proto3" json:"certificate_format,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Task) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Task) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetTriggerOn() TaskTrigger {
	if x != nil {
		return x.TriggerOn
	}
	return TaskTrigger_TASK_TRIGGER_UNSPECIFIED
}

func (x *Task) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Task) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Task) GetHeaders() string {
	if x != nil {
		return x.Headers
	}
	return ""
}

func (x *Task) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Task) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Task) GetLastRun() int64 {
	if x != nil {
		return x.LastRun
	}
	return 0
}

func (x *Task) GetLastStatus() string {
	if x != nil {
		return x.LastStatus
	}
	return ""
}

func (x *Task) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Task) GetIncludeCertificate() bool {
	if x != nil {
		return x.IncludeCertificate
	}
	return false
}

func (x *Task) GetCertificateFormat() string {
	if x != nil {
		return x.CertificateFormat
	}
	return ""
}

type TaskList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskList) Reset() {
	*x = TaskList{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskList) ProtoMessage() {}

func (x *TaskList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskList.ProtoReflect.Descriptor instead.
func (*TaskList) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *TaskList) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDelete) Reset() {
	*x = TaskDelete{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDelete) ProtoMessage() {}

func (x *TaskDelete) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDelete.ProtoReflect.Descriptor instead.
func (*TaskDelete) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *TaskDelete) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *TaskResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Zone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RecordCount   int64                  `protobuf:"varint,3,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *Zone) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Zone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Zone) GetRecordCount() int64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

type ZoneList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zones         []*Zone                `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneList) Reset() {
	*x = ZoneList{}
	mi := &file_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneList) ProtoMessage() {}

func (x *ZoneList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneList.ProtoReflect.Descriptor instead.
func (*ZoneList) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *ZoneList) GetZones() []*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

type Resolution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	ResponseTime  int64                  `protobuf:"varint,3,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resolution) Reset() {
	*x = Resolution{}
	mi := &file_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resolution) ProtoMessage() {}

func (x *Resolution) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resolution.ProtoReflect.Descriptor instead.
func (*Resolution) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{19}
}

func (x *Resolution) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Resolution) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Resolution) GetResponseTime() int64 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

func (x *Resolution) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ResolutionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resolutions   []*Resolution          `protobuf:"bytes,1,rep,name=resolutions,proto3" json:"resolutions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolutionResult) Reset() {
	*x = ResolutionResult{}
	mi := &file_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolutionResult) ProtoMessage() {}

func (x *ResolutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolutionResult.ProtoReflect.Descriptor instead.
func (*ResolutionResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{20}
}

func (x *ResolutionResult) GetResolutions() []*Resolution {
	if x != nil {
		return x.Resolutions
	}
	return nil
}

type Configuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogLevel      int32                  `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	RefreshCron   string                 `protobuf:"bytes,2,opt,name=refresh_cron,json=refreshCron,proto3" json:"refresh_cron,omitempty"`
	DnsServers    []string               `protobuf:"bytes,3,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`
	Ipv4Resolvers []string               `protobuf:"bytes,4,rep,name=ipv4_resolvers,json=ipv4Resolvers,proto3" json:"ipv4_resolvers,omitempty"`
	Ipv6Resolvers []string               `protobuf:"bytes,5,rep,name=ipv6_resolvers,json=ipv6Resolvers,proto3" json:"ipv6_resolvers,omitempty"`
	// User-facing notification settings. SMTP transport (host, port, auth, TLS,
	// from address, ...) is intentionally NOT part of this message and is
	// configured via the YAML file only.
	NotificationsEnabled         bool     `protobuf:"varint,6,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	NotificationsOnSuccess       bool     `protobuf:"varint,7,opt,name=notifications_on_success,json=notificationsOnSuccess,proto3" json:"notifications_on_success,omitempty"`
	NotificationsRecipients      []string `protobuf:"bytes,8,rep,name=notifications_recipients,json=notificationsRecipients,proto3" json:"notifications_recipients,omitempty"`
	NotificationsCooldownMinutes int32    `protobuf:"varint,9,opt,name=notifications_cooldown_minutes,json=notificationsCooldownMinutes,proto3" json:"notifications_cooldown_minutes,omitempty"`
	NotificationsSubjectPrefix   string   `protobuf:"bytes,10,opt,name=notifications_subject_prefix,json=notificationsSubjectPrefix,proto3" json:"notifications_subject_prefix,omitempty"`
	// ACME / Let's Encrypt settings for DNS-01 certificate issuance.
	AcmeEnabled         bool   `protobuf:"varint,11,opt,name=acme_enabled,json=acmeEnabled,proto3" json:"acme_enabled,omitempty"`
	AcmeEmail           string `protobuf:"bytes,12,opt,name=acme_email,json=acmeEmail,proto3" json:"acme_email,omitempty"`
	AcmeStaging         bool   `protobuf:"varint,13,opt,name=acme_staging,json=acmeStaging,proto3" json:"acme_staging,omitempty"`
	AcmeRenewBeforeDays int32  `protobuf:"varint,14,opt,name=acme_renew_before_days,json=acmeRenewBeforeDays,proto3" json:"acme_renew_before_days,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{21}
}

func (x *Configuration) GetLogLevel() int32 {
	if x != nil {
		return x.LogLevel
	}
	return 0
}

func (x *Configuration) GetRefreshCron() string {
	if x != nil {
		return x.RefreshCron
	}
	return ""
}

func (x *Configuration) GetDnsServers() []string {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

func (x *Configuration) GetIpv4Resolvers() []string {
	if x != nil {
		return x.Ipv4Resolvers
	}
	return nil
}

func (x *Configuration) GetIpv6Resolvers() []string {
	if x != nil {
		return x.Ipv6Resolvers
	}
	return nil
}

func (x *Configuration) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *Configuration) GetNotificationsOnSuccess() bool {
	if x != nil {
		return x.NotificationsOnSuccess
	}
	return false
}

func (x *Configuration) GetNotificationsRecipients() []string {
	if x != nil {
		return x.NotificationsRecipients
	}
	return nil
}

func (x *Configuration) GetNotificationsCooldownMinutes() int32 {
	if x != nil {
		return x.NotificationsCooldownMinutes
	}
	return 0
}

func (x *Configuration) GetNotificationsSubjectPrefix() string {
	if x != nil {
		return x.NotificationsSubjectPrefix
	}
	return ""
}

func (x *Configuration) GetAcmeEnabled() bool {
	if x != nil {
		return x.AcmeEnabled
	}
	return false
}

func (x *Configuration) GetAcmeEmail() string {
	if x != nil {
		return x.AcmeEmail
	}
	return ""
}

func (x *Configuration) GetAcmeStaging() bool {
	if x != nil {
		return x.AcmeStaging
	}
	return false
}

func (x *Configuration) GetAcmeRenewBeforeDays() int32 {
	if x != nil {
		return x.AcmeRenewBeforeDays
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{22}
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\aservice\"\a\n" +
	"\x05Empty\"!\n" +
	"\aRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\"\x99\x01\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12\x12\n" +
	"\x04ipv4\x18\x04 \x01(\tR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\x05 \x01(\tR\x04ipv6\x12\x18\n" +
	"\acurrent\x18\x06 \x01(\bR\acurrent\"@\n" +
	"\x0eAddressHistory\x12.\n" +
	"\taddresses\x18\x01 \x03(\v2\x10.service.AddressR\taddresses\"\xa3\x03\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x17\n" +
	"\azone_id\x18\x05 \x01(\x03R\x06zoneId\x12\x16\n" +
	"\x06domain\x18\x06 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x10\n" +
	"\x03ttl\x18\b \x01(\rR\x03ttl\x12\x1d\n" +
	"\n" +
	"address_id\x18\t \x01(\x03R\taddressId\x12*\n" +
	"\aaddress\x18\n" +
	" \x01(\v2\x10.service.AddressR\aaddress\x120\n" +
	"\apurpose\x18\v \x01(\x0e2\x16.service.RecordPurposeR\apurpose\x12)\n" +
	"\x10include_wildcard\x18\f \x01(\bR\x0fincludeWildcard\x126\n" +
	"\vcertificate\x18\r \x01(\v2\x14.service.CertificateR\vcertificate\"7\n" +
	"\n" +
	"RecordList\x12)\n" +
	"\arecords\x18\x01 \x03(\v2\x0f.service.RecordR\arecords\"g\n" +
	"\fRecordDelete\x12'\n" +
	"\x06record\x18\x01 \x01(\v2\x0f.service.RecordR\x06record\x12.\n" +
	"\x13delete_from_hetzner\x18\x02 \x01(\bR\x11deleteFromHetzner\"\x9d\x02\n" +
	"\vCertificate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12\x1b\n" +
	"\trecord_id\x18\x04 \x01(\x03R\brecordId\x12\x18\n" +
	"\adomains\x18\x05 \x01(\tR\adomains\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"not_before\x18\a \x01(\x03R\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\b \x01(\x03R\bnotAfter\x12\x16\n" +
	"\x06serial\x18\t \x01(\tR\x06serial\x12\x1d\n" +
	"\n" +
	"last_error\x18\n" +
	" \x01(\tR\tlastError\"K\n" +
	"\x0fCertificateList\x128\n" +
	"\fcertificates\x18\x01 \x03(\v2\x14.service.CertificateR\fcertificates\"~\n" +
	"\x13CertificateArtifact\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable\x12!\n" +
	"\fdownload_url\x18\x04 \x01(\tR\vdownloadUrl\"\xf6\x01\n" +
	"\x16CertificateIssuanceJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x05 \x01(\x03R\n" +
	"finishedAt\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12%\n" +
	"\x0ecertificate_id\x18\b \x01(\x03R\rcertificateId\"\xc0\x02\n" +
	"\x12CertificateTaskRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x1b\n" +
	"\ttask_name\x18\x03 \x01(\tR\btaskName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12'\n" +
	"\x0fresponse_status\x18\x05 \x01(\tR\x0eresponseStatus\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\b \x01(\x03R\n" +
	"finishedAt\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x03R\n" +
	"durationMs\x12,\n" +
	"\x12certificate_job_id\x18\n" +
	" \x01(\x03R\x10certificateJobId\"\x8a\x03\n" +
	"\x12CertificateDetails\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\x03R\brecordId\x12\x1f\n" +
	"\vrecord_name\x18\x02 \x01(\tR\n" +
	"recordName\x12#\n" +
	"\rrecord_domain\x18\x03 \x01(\tR\frecordDomain\x126\n" +
	"\vcertificate\x18\x04 \x01(\v2\x14.service.CertificateR\vcertificate\x12:\n" +
	"\tartifacts\x18\x05 \x03(\v2\x1c.service.CertificateArtifactR\tartifacts\x12D\n" +
	"\rissuance_jobs\x18\x06 \x03(\v2\x1f.service.CertificateIssuanceJobR\fissuanceJobs\x128\n" +
	"\ttask_runs\x18\a \x03(\v2\x1b.service.CertificateTaskRunR\btaskRuns\x12\x1d\n" +
	"\n" +
	"fetched_at\x18\b \x01(\x03R\tfetchedAt\"\xe7\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12\x1b\n" +
	"\trecord_id\x18\x04 \x01(\x03R\brecordId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x123\n" +
	"\n" +
	"trigger_on\x18\x06 \x01(\x0e2\x14.service.TaskTriggerR\ttriggerOn\x12\x16\n" +
	"\x06method\x18\a \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\x12\x18\n" +
	"\aheaders\x18\t \x01(\tR\aheaders\x12\x12\n" +
	"\x04body\x18\n" +
	" \x01(\tR\x04body\x12\x18\n" +
	"\aenabled\x18\v \x01(\bR\aenabled\x12\x19\n" +
	"\blast_run\x18\f \x01(\x03R\alastRun\x12\x1f\n" +
	"\vlast_status\x18\r \x01(\tR\n" +
	"lastStatus\x12\x1d\n" +
	"\n" +
	"last_error\x18\x0e \x01(\tR\tlastError\x12/\n" +
	"\x13include_certificate\x18\x0f \x01(\bR\x12includeCertificate\x12-\n" +
	"\x12certificate_format\x18\x10 \x01(\tR\x11certificateFormat\"/\n" +
	"\bTaskList\x12#\n" +
	"\x05tasks\x18\x01 \x03(\v2\r.service.TaskR\x05tasks\"\x1c\n" +
	"\n" +
	"TaskDelete\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\n" +
	"TaskResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"M\n" +
	"\x04Zone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\frecord_count\x18\x03 \x01(\x03R\vrecordCount\"/\n" +
	"\bZoneList\x12#\n" +
	"\x05zones\x18\x01 \x03(\v2\r.service.ZoneR\x05zones\"}\n" +
	"\n" +
	"Resolution\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12#\n" +
	"\rresponse_time\x18\x03 \x01(\x03R\fresponseTime\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"I\n" +
	"\x10ResolutionResult\x125\n" +
	"\vresolutions\x18\x01 \x03(\v2\x13.service.ResolutionR\vresolutions\"\x8a\x05\n" +
	"\rConfiguration\x12\x1b\n" +
	"\tlog_level\x18\x01 \x01(\x05R\blogLevel\x12!\n" +
	"\frefresh_cron\x18\x02 \x01(\tR\vrefreshCron\x12\x1f\n" +
	"\vdns_servers\x18\x03 \x03(\tR\n" +
	"dnsServers\x12%\n" +
	"\x0eipv4_resolvers\x18\x04 \x03(\tR\ripv4Resolvers\x12%\n" +
	"\x0eipv6_resolvers\x18\x05 \x03(\tR\ripv6Resolvers\x123\n" +
	"\x15notifications_enabled\x18\x06 \x01(\bR\x14notificationsEnabled\x128\n" +
	"\x18notifications_on_success\x18\a \x01(\bR\x16notificationsOnSuccess\x129\n" +
	"\x18notifications_recipients\x18\b \x03(\tR\x17notificationsRecipients\x12D\n" +
	"\x1enotifications_cooldown_minutes\x18\t \x01(\x05R\x1cnotificationsCooldownMinutes\x12@\n" +
	"\x1cnotifications_subject_prefix\x18\n" +
	" \x01(\tR\x1anotificationsSubjectPrefix\x12!\n" +
	"\facme_enabled\x18\v \x01(\bR\vacmeEnabled\x12\x1d\n" +
	"\n" +
	"acme_email\x18\f \x01(\tR\tacmeEmail\x12!\n" +
	"\facme_staging\x18\r \x01(\bR\vacmeStaging\x123\n" +
	"\x16acme_renew_before_days\x18\x0e \x01(\x05R\x13acmeRenewBeforeDays\"X\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*z\n" +
	"\rRecordPurpose\x12\x1e\n" +
	"\x1aRECORD_PURPOSE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RECORD_PURPOSE_DDNS\x10\x01\x12\x17\n" +
	"\x13RECORD_PURPOSE_CERT\x10\x02\x12\x17\n" +
	"\x13RECORD_PURPOSE_BOTH\x10\x03*n\n" +
	"\vTaskTrigger\x12\x1c\n" +
	"\x18TASK_TRIGGER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTASK_TRIGGER_IP\x10\x01\x12\x15\n" +
	"\x11TASK_TRIGGER_CERT\x10\x02\x12\x15\n" +
	"\x11TASK_TRIGGER_BOTH\x10\x032\x84\t\n" +
	"\x04HDNS\x12.\n" +
	"\bGetZones\x12\x0f.service.Record\x1a\x11.service.ZoneList\x123\n" +
	"\n" +
	"GetRecords\x12\x10.service.Request\x1a\x13.service.RecordList\x120\n" +
	"\fUpsertRecord\x12\x0f.service.Record\x1a\x0f.service.Record\x125\n" +
	"\fDeleteRecord\x12\x15.service.RecordDelete\x1a\x0e.service.Empty\x121\n" +
	"\rRefreshRecord\x12\x0f.service.Record\x1a\x0f.service.Record\x127\n" +
	"\x12FetchHetznerRecord\x12\x0f.service.Record\x1a\x10.service.Address\x12;\n" +
	"\rResolveRecord\x12\x0f.service.Record\x1a\x19.service.ResolutionResult\x12=\n" +
	"\x13StreamResolveRecord\x12\x0f.service.Record\x1a\x13.service.Resolution0\x01\x123\n" +
	"\rStreamAddress\x12\x0e.service.Empty\x1a\x10.service.Address0\x01\x12.\n" +
	"\n" +
	"GetAddress\x12\x0e.service.Empty\x1a\x10.service.Address\x12<\n" +
	"\x11GetAddressHistory\x12\x0e.service.Empty\x1a\x17.service.AddressHistory\x122\n" +
	"\x0eRefreshAddress\x12\x0e.service.Empty\x1a\x10.service.Address\x12;\n" +
	"\x0fGetCertificates\x12\x0e.service.Empty\x1a\x18.service.CertificateList\x129\n" +
	"\x10IssueCertificate\x12\x0f.service.Record\x1a\x14.service.Certificate\x12E\n" +
	"\x15GetCertificateDetails\x12\x0f.service.Record\x1a\x1b.service.CertificateDetails\x12-\n" +
	"\bGetTasks\x12\x0e.service.Empty\x1a\x11.service.TaskList\x12*\n" +
	"\n" +
	"UpsertTask\x12\r.service.Task\x1a\r.service.Task\x121\n" +
	"\n" +
	"DeleteTask\x12\x13.service.TaskDelete\x1a\x0e.service.Empty\x12-\n" +
	"\aRunTask\x12\r.service.Task\x1a\x13.service.TaskResult\x123\n" +
	"\tGetConfig\x12\x0e.service.Empty\x1a\x16.service.Configuration\x12>\n" +
	"\fUpdateConfig\x12\x16.service.Configuration\x1a\x16.service.ConfigurationB5H\x01Z1github.com/valentin-kaiser/hdns/pkg/proto/serviceb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_goTypes = []any{
	(RecordPurpose)(0),             // 0: service.RecordPurpose
	(TaskTrigger)(0),               // 1: service.TaskTrigger
	(*Empty)(nil),                  // 2: service.Empty
	(*Request)(nil),                // 3: service.Request
	(*Address)(nil),                // 4: service.Address
	(*AddressHistory)(nil),         // 5: service.AddressHistory
	(*Record)(nil),                 // 6: service.Record
	(*RecordList)(nil),             // 7: service.RecordList
	(*RecordDelete)(nil),           // 8: service.RecordDelete
	(*Certificate)(nil),            // 9: service.Certificate
	(*CertificateList)(nil),        // 10: service.CertificateList
	(*CertificateArtifact)(nil),    // 11: service.CertificateArtifact
	(*CertificateIssuanceJob)(nil), // 12: service.CertificateIssuanceJob
	(*CertificateTaskRun)(nil),     // 13: service.CertificateTaskRun
	(*CertificateDetails)(nil),     // 14: service.CertificateDetails
	(*Task)(nil),                   // 15: service.Task
	(*TaskList)(nil),               // 16: service.TaskList
	(*TaskDelete)(nil),             // 17: service.TaskDelete
	(*TaskResult)(nil),             // 18: service.TaskResult
	(*Zone)(nil),                   // 19: service.Zone
	(*ZoneList)(nil),               // 20: service.ZoneList
	(*Resolution)(nil),             // 21: service.Resolution
	(*ResolutionResult)(nil),       // 22: service.ResolutionResult
	(*Configuration)(nil),          // 23: service.Configuration
	(*LogEntry)(nil),               // 24: service.LogEntry
}
var file_api_proto_depIdxs = []int32{
	4,  // 0: service.AddressHistory.addresses:type_name -> service.Address
	4,  // 1: service.Record.address:type_name -> service.Address
	0,  // 2: service.Record.purpose:type_name -> service.RecordPurpose
	9,  // 3: service.Record.certificate:type_name -> service.Certificate
	6,  // 4: service.RecordList.records:type_name -> service.Record
	6,  // 5: service.RecordDelete.record:type_name -> service.Record
	9,  // 6: service.CertificateList.certificates:type_name -> service.Certificate
	9,  // 7: service.CertificateDetails.certificate:type_name -> service.Certificate
	11, // 8: service.CertificateDetails.artifacts:type_name -> service.CertificateArtifact
	12, // 9: service.CertificateDetails.issuance_jobs:type_name -> service.CertificateIssuanceJob
	13, // 10: service.CertificateDetails.task_runs:type_name -> service.CertificateTaskRun
	1,  // 11: service.Task.trigger_on:type_name -> service.TaskTrigger
	15, // 12: service.TaskList.tasks:type_name -> service.Task
	19, // 13: service.ZoneList.zones:type_name -> service.Zone
	21, // 14: service.ResolutionResult.resolutions:type_name -> service.Resolution
	6,  // 15: service.HDNS.GetZones:input_type -> service.Record
	3,  // 16: service.HDNS.GetRecords:input_type -> service.Request
	6,  // 17: service.HDNS.UpsertRecord:input_type -> service.Record
	8,  // 18: service.HDNS.DeleteRecord:input_type -> service.RecordDelete
	6,  // 19: service.HDNS.RefreshRecord:input_type -> service.Record
	6,  // 20: service.HDNS.FetchHetznerRecord:input_type -> service.Record
	6,  // 21: service.HDNS.ResolveRecord:input_type -> service.Record
	6,  // 22: service.HDNS.StreamResolveRecord:input_type -> service.Record
	2,  // 23: service.HDNS.StreamAddress:input_type -> service.Empty
	2,  // 24: service.HDNS.GetAddress:input_type -> service.Empty
	2,  // 25: service.HDNS.GetAddressHistory:input_type -> service.Empty
	2,  // 26: service.HDNS.RefreshAddress:input_type -> service.Empty
	2,  // 27: service.HDNS.GetCertificates:input_type -> service.Empty
	6,  // 28: service.HDNS.IssueCertificate:input_type -> service.Record
	6,  // 29: service.HDNS.GetCertificateDetails:input_type -> service.Record
	2,  // 30: service.HDNS.GetTasks:input_type -> service.Empty
	15, // 31: service.HDNS.UpsertTask:input_type -> service.Task
	17, // 32: service.HDNS.DeleteTask:input_type -> service.TaskDelete
	15, // 33: service.HDNS.RunTask:input_type -> service.Task
	2,  // 34: service.HDNS.GetConfig:input_type -> service.Empty
	23, // 35: service.HDNS.UpdateConfig:input_type -> service.Configuration
	20, // 36: service.HDNS.GetZones:output_type -> service.ZoneList
	7,  // 37: service.HDNS.GetRecords:output_type -> service.RecordList
	6,  // 38: service.HDNS.UpsertRecord:output_type -> service.Record
	2,  // 39: service.HDNS.DeleteRecord:output_type -> service.Empty
	6,  // 40: service.HDNS.RefreshRecord:output_type -> service.Record
	4,  // 41: service.HDNS.FetchHetznerRecord:output_type -> service.Address
	22, // 42: service.HDNS.ResolveRecord:output_type -> service.ResolutionResult
	21, // 43: service.HDNS.StreamResolveRecord:output_type -> service.Resolution
	4,  // 44: service.HDNS.StreamAddress:output_type -> service.Address
	4,  // 45: service.HDNS.GetAddress:output_type -> service.Address
	5,  // 46: service.HDNS.GetAddressHistory:output_type -> service.AddressHistory
	4,  // 47: service.HDNS.RefreshAddress:output_type -> service.Address
	10, // 48: service.HDNS.GetCertificates:output_type -> service.CertificateList
	9,  // 49: service.HDNS.IssueCertificate:output_type -> service.Certificate
	14, // 50: service.HDNS.GetCertificateDetails:output_type -> service.CertificateDetails
	16, // 51: service.HDNS.GetTasks:output_type -> service.TaskList
	15, // 52: service.HDNS.UpsertTask:output_type -> service.Task
	2,  // 53: service.HDNS.DeleteTask:output_type -> service.Empty
	18, // 54: service.HDNS.RunTask:output_type -> service.TaskResult
	23, // 55: service.HDNS.GetConfig:output_type -> service.Configuration
	23, // 56: service.HDNS.UpdateConfig:output_type -> service.Configuration
	36, // [36:57] is the sub-list for method output_type
	15, // [15:36] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
