// Code generated by protoc-gen-go-jrpc. DO NOT EDIT.
// source: api.proto

package service

import (
	"context"
	"errors"
	"github.com/valentin-kaiser/go-core/web/jrpc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"net/url"
)

// HDNSServer is the server API for HDNS service.
type HDNSServer interface {
	Descriptor() protoreflect.FileDescriptor
	GetZones(ctx context.Context, in *ZoneRequest) (*ZoneList, error)
	GetRecords(ctx context.Context, in *Request) (*RecordList, error)
	UpsertRecord(ctx context.Context, in *Record) (*Record, error)
	DeleteRecord(ctx context.Context, in *RecordDelete) (*Empty, error)
	RefreshRecord(ctx context.Context, in *Record) (*Record, error)
	ResolveRecord(ctx context.Context, in *Record) (*ResolutionResult, error)
	StreamResolveRecord(ctx context.Context, in *Record, out chan<- *Resolution) error
	StreamAddress(ctx context.Context, in *Empty, out chan<- *Address) error
	GetAddress(ctx context.Context, in *Empty) (*Address, error)
	GetAddressHistory(ctx context.Context, in *Empty) (*AddressHistory, error)
	RefreshAddress(ctx context.Context, in *Empty) (*Address, error)
	GetConfig(ctx context.Context, in *Empty) (*Configuration, error)
	UpdateConfig(ctx context.Context, in *Configuration) (*Configuration, error)
}

type UnimplementedHDNSServer struct{}

func (UnimplementedHDNSServer) Descriptor() protoreflect.FileDescriptor {
	return File_api_proto
}

func (UnimplementedHDNSServer) GetZones(ctx context.Context, in *ZoneRequest) (*ZoneList, error) {
	return nil, errors.New("method HDNS.GetZones not implemented")
}

func (UnimplementedHDNSServer) GetRecords(ctx context.Context, in *Request) (*RecordList, error) {
	return nil, errors.New("method HDNS.GetRecords not implemented")
}

func (UnimplementedHDNSServer) UpsertRecord(ctx context.Context, in *Record) (*Record, error) {
	return nil, errors.New("method HDNS.UpsertRecord not implemented")
}

func (UnimplementedHDNSServer) DeleteRecord(ctx context.Context, in *RecordDelete) (*Empty, error) {
	return nil, errors.New("method HDNS.DeleteRecord not implemented")
}

func (UnimplementedHDNSServer) RefreshRecord(ctx context.Context, in *Record) (*Record, error) {
	return nil, errors.New("method HDNS.RefreshRecord not implemented")
}

func (UnimplementedHDNSServer) ResolveRecord(ctx context.Context, in *Record) (*ResolutionResult, error) {
	return nil, errors.New("method HDNS.ResolveRecord not implemented")
}

func (UnimplementedHDNSServer) StreamResolveRecord(ctx context.Context, in *Record, out chan<- *Resolution) error {
	return errors.New("method HDNS.StreamResolveRecord not implemented")
}

func (UnimplementedHDNSServer) StreamAddress(ctx context.Context, in *Empty, out chan<- *Address) error {
	return errors.New("method HDNS.StreamAddress not implemented")
}

func (UnimplementedHDNSServer) GetAddress(ctx context.Context, in *Empty) (*Address, error) {
	return nil, errors.New("method HDNS.GetAddress not implemented")
}

func (UnimplementedHDNSServer) GetAddressHistory(ctx context.Context, in *Empty) (*AddressHistory, error) {
	return nil, errors.New("method HDNS.GetAddressHistory not implemented")
}

func (UnimplementedHDNSServer) RefreshAddress(ctx context.Context, in *Empty) (*Address, error) {
	return nil, errors.New("method HDNS.RefreshAddress not implemented")
}

func (UnimplementedHDNSServer) GetConfig(ctx context.Context, in *Empty) (*Configuration, error) {
	return nil, errors.New("method HDNS.GetConfig not implemented")
}

func (UnimplementedHDNSServer) UpdateConfig(ctx context.Context, in *Configuration) (*Configuration, error) {
	return nil, errors.New("method HDNS.UpdateConfig not implemented")
}

// RegisterHDNSServer registers a HDNSServer with the JSON-RPC service registry.
// It returns a *jrpc.Service that can be used to handle JSON-RPC requests.
func RegisterHDNSServer(server HDNSServer) *jrpc.Service {
	return jrpc.Register(server)
}

// Ensure UnimplementedHDNSServer implements HDNSServer
var _ HDNSServer = (*UnimplementedHDNSServer)(nil)

// HDNSClientDefinition is the client API for HDNS service.
type HDNSClientDefinition interface {
	GetZones(ctx context.Context, in *ZoneRequest) (*ZoneList, error)
	GetRecords(ctx context.Context, in *Request) (*RecordList, error)
	UpsertRecord(ctx context.Context, in *Record) (*Record, error)
	DeleteRecord(ctx context.Context, in *RecordDelete) (*Empty, error)
	RefreshRecord(ctx context.Context, in *Record) (*Record, error)
	ResolveRecord(ctx context.Context, in *Record) (*ResolutionResult, error)
	StreamResolveRecord(ctx context.Context, in *Record, out chan<- *Resolution) error
	StreamAddress(ctx context.Context, in *Empty, out chan<- *Address) error
	GetAddress(ctx context.Context, in *Empty) (*Address, error)
	GetAddressHistory(ctx context.Context, in *Empty) (*AddressHistory, error)
	RefreshAddress(ctx context.Context, in *Empty) (*Address, error)
	GetConfig(ctx context.Context, in *Empty) (*Configuration, error)
	UpdateConfig(ctx context.Context, in *Configuration) (*Configuration, error)
}

type HDNSClient struct {
	client  *jrpc.Client
	baseURL *url.URL
}

// NewHDNSClient creates a new client for the HDNS service.
// It parses and validates the baseURL, returning an error if the URL is malformed.
func NewHDNSClient(baseURL string, opts ...jrpc.ClientOption) (*HDNSClient, error) {
	parsedURL, err := url.Parse(baseURL)
	if err != nil {
		return nil, err
	}
	return &HDNSClient{
		client:  jrpc.NewClient(opts...),
		baseURL: parsedURL,
	}, nil
}

func (c *HDNSClient) GetZones(ctx context.Context, in *ZoneRequest) (*ZoneList, error) {
	u := c.baseURL.JoinPath("HDNS", "GetZones")
	out := &ZoneList{}
	err := c.client.Call(ctx, u, in, out, nil)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *HDNSClient) GetRecords(ctx context.Context, in *Request) (*RecordList, error) {
	u := c.baseURL.JoinPath("HDNS", "GetRecords")
	out := &RecordList{}
	err := c.client.Call(ctx, u, in, out, nil)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *HDNSClient) UpsertRecord(ctx context.Context, in *Record) (*Record, error) {
	u := c.baseURL.JoinPath("HDNS", "UpsertRecord")
	out := &Record{}
	err := c.client.Call(ctx, u, in, out, nil)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *HDNSClient) DeleteRecord(ctx context.Context, in *RecordDelete) (*Empty, error) {
	u := c.baseURL.JoinPath("HDNS", "DeleteRecord")
	out := &Empty{}
	err := c.client.Call(ctx, u, in, out, nil)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *HDNSClient) RefreshRecord(ctx context.Context, in *Record) (*Record, error) {
	u := c.baseURL.JoinPath("HDNS", "RefreshRecord")
	out := &Record{}
	err := c.client.Call(ctx, u, in, out, nil)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *HDNSClient) ResolveRecord(ctx context.Context, in *Record) (*ResolutionResult, error) {
	u := c.baseURL.JoinPath("HDNS", "ResolveRecord")
	out := &ResolutionResult{}
	err := c.client.Call(ctx, u, in, out, nil)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *HDNSClient) StreamResolveRecord(ctx context.Context, in *Record, out chan<- *Resolution) error {
	u := c.baseURL.JoinPath("HDNS", "StreamResolveRecord")
	factory := func() *Resolution { return &Resolution{} }
	return jrpc.ServerStream(c.client, ctx, u, in, out, factory)
}

func (c *HDNSClient) StreamAddress(ctx context.Context, in *Empty, out chan<- *Address) error {
	u := c.baseURL.JoinPath("HDNS", "StreamAddress")
	factory := func() *Address { return &Address{} }
	return jrpc.ServerStream(c.client, ctx, u, in, out, factory)
}

func (c *HDNSClient) GetAddress(ctx context.Context, in *Empty) (*Address, error) {
	u := c.baseURL.JoinPath("HDNS", "GetAddress")
	out := &Address{}
	err := c.client.Call(ctx, u, in, out, nil)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *HDNSClient) GetAddressHistory(ctx context.Context, in *Empty) (*AddressHistory, error) {
	u := c.baseURL.JoinPath("HDNS", "GetAddressHistory")
	out := &AddressHistory{}
	err := c.client.Call(ctx, u, in, out, nil)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *HDNSClient) RefreshAddress(ctx context.Context, in *Empty) (*Address, error) {
	u := c.baseURL.JoinPath("HDNS", "RefreshAddress")
	out := &Address{}
	err := c.client.Call(ctx, u, in, out, nil)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *HDNSClient) GetConfig(ctx context.Context, in *Empty) (*Configuration, error) {
	u := c.baseURL.JoinPath("HDNS", "GetConfig")
	out := &Configuration{}
	err := c.client.Call(ctx, u, in, out, nil)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *HDNSClient) UpdateConfig(ctx context.Context, in *Configuration) (*Configuration, error) {
	u := c.baseURL.JoinPath("HDNS", "UpdateConfig")
	out := &Configuration{}
	err := c.client.Call(ctx, u, in, out, nil)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Ensure HDNSClient implements HDNSClientDefinition
var _ HDNSClientDefinition = (*HDNSClient)(nil)
